import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";

const config = JSON.parse(await readFile(new URL("../src-tauri/tauri.conf.json", import.meta.url), "utf8"));
const windowsConfigUrl = new URL("../src-tauri/tauri.windows.conf.json", import.meta.url);
const windowsConfig = existsSync(windowsConfigUrl) ? JSON.parse(await readFile(windowsConfigUrl, "utf8")) : {};
const linuxConfigUrl = new URL("../src-tauri/tauri.linux.conf.json", import.meta.url);
const linuxConfig = existsSync(linuxConfigUrl) ? JSON.parse(await readFile(linuxConfigUrl, "utf8")) : {};
const macosConfigUrl = new URL("../src-tauri/tauri.macos.conf.json", import.meta.url);
const macosConfig = existsSync(macosConfigUrl) ? JSON.parse(await readFile(macosConfigUrl, "utf8")) : {};
const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const indexHtml = await readFile(new URL("../index.html", import.meta.url), "utf8");
const appSource = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const i18nSource = await readFile(new URL("../src/i18n.ts", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const mainSource = await readFile(new URL("../src-tauri/src/main.rs", import.meta.url), "utf8");
const tauriLibSource = await readFile(new URL("../src-tauri/src/lib.rs", import.meta.url), "utf8");
const playbackStoreUrl = new URL("../src-tauri/src/playback_store.rs", import.meta.url);
const playbackStoreSource = existsSync(playbackStoreUrl) ? await readFile(playbackStoreUrl, "utf8") : "";
const appearanceStoreUrl = new URL("../src-tauri/src/appearance_store.rs", import.meta.url);
const appearanceStoreSource = existsSync(appearanceStoreUrl) ? await readFile(appearanceStoreUrl, "utf8") : "";
const mediaPathsUrl = new URL("../src-tauri/src/media_paths.rs", import.meta.url);
const mediaPathsSource = existsSync(mediaPathsUrl) ? await readFile(mediaPathsUrl, "utf8") : "";
const platformSupportUrl = new URL("../src-tauri/src/platform_support.rs", import.meta.url);
const platformSupportSource = existsSync(platformSupportUrl) ? await readFile(platformSupportUrl, "utf8") : "";
const shellPreviewUrl = new URL("../src-tauri/src/shell_preview.rs", import.meta.url);
const shellPreviewSource = existsSync(shellPreviewUrl) ? await readFile(shellPreviewUrl, "utf8") : "";
const capability = JSON.parse(await readFile(new URL("../src-tauri/capabilities/default.json", import.meta.url), "utf8"));
const ciWorkflow = await readFile(new URL("../../../.github/workflows/ci.yml", import.meta.url), "utf8");
const releaseWorkflowUrl = new URL("../../../.github/workflows/release.yml", import.meta.url);
const releaseWorkflow = existsSync(releaseWorkflowUrl) ? await readFile(releaseWorkflowUrl, "utf8") : "";
const releaseVerifyScriptUrl = new URL("./verify-release.mjs", import.meta.url);
const macosBundleScriptUrl = new URL("./bundle-macos-libmpv.mjs", import.meta.url);
const macosBundleScriptSource = existsSync(macosBundleScriptUrl) ? await readFile(macosBundleScriptUrl, "utf8") : "";
const releaseMpvManifestUrl = new URL("../../../docs/native-deps/mpv-windows-x64.json", import.meta.url);
const workspaceToml = await readFile(new URL("../../../Cargo.toml", import.meta.url), "utf8");
const tauriCargoToml = await readFile(new URL("../src-tauri/Cargo.toml", import.meta.url), "utf8");
const tauriBuildScript = await readFile(new URL("../src-tauri/build.rs", import.meta.url), "utf8");
const nsisHooksUrl = new URL("../src-tauri/nsis-hooks.nsh", import.meta.url);
const nsisHooksSource = existsSync(nsisHooksUrl) ? await readFile(nsisHooksUrl, "utf8") : "";
const mpvEmbedUrl = new URL("../src-tauri/src/mpv_embed.rs", import.meta.url);
const mpvEmbedSource = existsSync(mpvEmbedUrl) ? await readFile(mpvEmbedUrl, "utf8") : "";
const macosGlViewUrl = new URL("../src-tauri/src/macos_mpv_gl_view.m", import.meta.url);
const macosGlViewSource = existsSync(macosGlViewUrl) ? await readFile(macosGlViewUrl, "utf8") : "";
const mpvRenderFiles = [
  new URL("../src-tauri/src/mpv_render.rs", import.meta.url),
  new URL("../src-tauri/src/mpv_render/sys.rs", import.meta.url),
  new URL("../src-tauri/src/mpv_render/win32_surface.rs", import.meta.url),
];
const rootLogoUrl = new URL("../../../openplayer_logo_10001000.png", import.meta.url);
const uiLogoUrl = new URL("../src/assets/openplayer-logo.png", import.meta.url);
const tauriIconPngUrl = new URL("../src-tauri/icons/icon.png", import.meta.url);
const tauriIconIcoUrl = new URL("../src-tauri/icons/icon.ico", import.meta.url);
const tauriIconIcnsUrl = new URL("../src-tauri/icons/icon.icns", import.meta.url);
const embedCommandPattern = /mpv_embed_open_path|mpv_embed_play|mpv_embed_pause|mpv_embed_seek|mpv_embed_set_volume|mpv_embed_set_speed|mpv_embed_select_track|mpv_embed_add_subtitle|mpv_embed_snapshot|mpv_embed_stop/;

function extractCfgFunction(source, cfgPattern, fnPattern) {
  const cfgMatch = cfgPattern.exec(source);
  if (!cfgMatch) {
    return "";
  }

  const afterCfg = cfgMatch.index + cfgMatch[0].length;
  const fnMatch = fnPattern.exec(source.slice(afterCfg));
  if (!fnMatch) {
    return "";
  }

  const fnStart = afterCfg + fnMatch.index;
  const openBrace = source.indexOf("{", fnStart + fnMatch[0].length);
  if (openBrace === -1) {
    return "";
  }

  let depth = 0;
  for (let index = openBrace; index < source.length; index += 1) {
    if (source[index] === "{") {
      depth += 1;
    } else if (source[index] === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(fnStart, index + 1);
      }
    }
  }

  return "";
}

function extractFunctionAt(source, fnStart) {
  const openBrace = source.indexOf("{", fnStart);
  if (openBrace === -1) {
    return "";
  }

  let depth = 0;
  for (let index = openBrace; index < source.length; index += 1) {
    if (source[index] === "{") {
      depth += 1;
    } else if (source[index] === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(fnStart, index + 1);
      }
    }
  }

  return "";
}

const mpvEmbedRunMatch = /#\[cfg\(\s*feature\s*=\s*"mpv-embed"\s*\)\]\s*pub\s+fn\s+run\s*\(\s*\)/.exec(tauriLibSource);
const mpvEmbedRunSource = mpvEmbedRunMatch
  ? extractFunctionAt(tauriLibSource, mpvEmbedRunMatch.index + mpvEmbedRunMatch[0].lastIndexOf("pub"))
  : "";
const windowToggleFullscreenMatch = /#\[tauri::command\]\s*fn\s+window_toggle_fullscreen\s*\(/.exec(tauriLibSource);
const windowToggleFullscreenSource = windowToggleFullscreenMatch
  ? extractFunctionAt(tauriLibSource, windowToggleFullscreenMatch.index + windowToggleFullscreenMatch[0].lastIndexOf("fn"))
  : "";
const windowApplyResizeDeltaMatch = /#\[tauri::command\]\s*fn\s+window_apply_resize_delta\s*\(/.exec(tauriLibSource);
const windowApplyResizeDeltaSource = windowApplyResizeDeltaMatch
  ? extractFunctionAt(tauriLibSource, windowApplyResizeDeltaMatch.index + windowApplyResizeDeltaMatch[0].lastIndexOf("fn"))
  : "";
const mpvSnapshotMatch = /fn\s+snapshot\s*\(/.exec(mpvEmbedSource);
const mpvSnapshotSource = mpvSnapshotMatch ? extractFunctionAt(mpvEmbedSource, mpvSnapshotMatch.index) : "";
const dragRegionSources = [
  "handleDragRegionPointerDown",
  "handleDragRegionPointerMove",
  "handleDragRegionPointerEnd",
  "handleDragRegionDoubleClick",
]
  .map((name) => {
    const match = new RegExp(`function\\s+${name}\\s*\\(`).exec(appSource);
    return match ? extractFunctionAt(appSource, match.index) : "";
  })
  .join("\n");

const [mainWindow] = config.app.windows;

assert.equal(config.app.windows.length, 1, "minimal shell should use one Tauri window from config");
assert.equal(mainWindow.url, "index.html?surface=video", "main window must be the video host surface");
assert.equal(mainWindow.decorations, false, "custom controls require custom window chrome once overlay is restored");
assert.equal(mainWindow.resizable, true, "main video window must remain freely resizable");
assert.equal(mainWindow.transparent, true, "video surface behind WebView requires transparent WebView/window composition");
assert.equal(config.app.security.csp, null, "minimal shell keeps the baseline CSP behavior");
assert.equal(config.app.security.assetProtocol, undefined, "minimal HTML playback must not expose Tauri asset protocol");
assert.equal(config.bundle?.resources, undefined, "base Tauri config must not require ignored Windows mpv DLL resources during Linux CI");
assert.equal(windowsConfig.bundle?.active, true, "Windows desktop release builds must produce an installer bundle by default");
assert.equal(windowsConfig.bundle?.targets, "nsis", "Windows desktop release build should target the NSIS installer");
assert.ok(Object.keys(windowsConfig.bundle?.resources ?? {}).some((resource) => resource.endsWith("libmpv-2.dll")), "Windows installer bundle must include the mpv runtime DLL");
assert.ok(windowsConfig.bundle?.fileAssociations?.some((association) => association.ext?.includes("mp4") && association.ext?.includes("mkv")), "Windows installer must register OpenPlayer as a handler for common media files");
assert.ok(windowsConfig.bundle?.fileAssociations?.some((association) => association.ext?.includes("mp3") && association.ext?.includes("wav") && association.ext?.includes("mp2") && association.ext?.includes("m4b")), "Windows installer must expose OpenPlayer as a default-app candidate for broad audio formats");
assert.equal(windowsConfig.bundle?.windows?.nsis?.installerHooks, "nsis-hooks.nsh", "NSIS installer must install mpv runtime DLL next to the app executable");
assert.match(nsisHooksSource, /CopyFiles[\s\S]*libmpv-2\.dll[\s\S]*\$INSTDIR\\libmpv-2\.dll/, "NSIS hooks must copy libmpv-2.dll beside the installed executable");
assert.match(nsisHooksSource, /Delete[\s\S]*\$INSTDIR\\libmpv-2\.dll/, "NSIS hooks must remove copied mpv runtime DLL during uninstall");
assert.match(nsisHooksSource, /OP_THUMBNAIL_HANDLER_GUID[\s\S]*e357fccd-a995-4576-b01f-234630154e96/i, "NSIS hooks must register the Windows thumbnail handler key for media previews");
assert.match(nsisHooksSource, /OP_PROPERTY_THUMBNAIL_HANDLER_CLSID[\s\S]*9DBD2C50-62AD-11D0-B806-00C04FD706EC/i, "NSIS hooks must reuse the system property thumbnail handler instead of shipping an Explorer-loaded DLL");
assert.match(nsisHooksSource, /OP_REGISTER_VIDEO_THUMBNAIL[\s\S]*WriteRegStr SHELL_CONTEXT "Software\\Classes\\\.\$\{EXT\}" "PerceivedType" "video"/, "NSIS hooks must mark video associations as video for Explorer thumbnails");
assert.match(nsisHooksSource, /OP_REGISTER_VIDEO_THUMBNAIL "mp4" "video\/mp4"/, "NSIS hooks must preserve Explorer video thumbnails for MP4 files");
assert.match(nsisHooksSource, /OP_REGISTER_VIDEO_THUMBNAIL "mkv" "video\/x-matroska"/, "NSIS hooks must preserve Explorer video thumbnails for MKV files");
assert.doesNotMatch(nsisHooksSource, /OP_REGISTER_VIDEO_THUMBNAIL "mxf" "application\/mxf"/, "NSIS hooks must not register every mpv video container by default");
assert.doesNotMatch(nsisHooksSource, /OP_REGISTER_AUDIO_METADATA "wv" "audio\/x-wavpack"/, "NSIS hooks must not register every mpv audio container by default");
assert.match(nsisHooksSource, /SystemFileAssociations\\video[\s\S]*"Treatment" 3[\s\S]*SystemFileAssociations\\video[\s\S]*"ThumbnailCutoff" 1/, "NSIS hooks must preserve Windows video thumbnail adornment metadata");
assert.match(nsisHooksSource, /UPDATEFILEASSOC/, "NSIS hooks must notify Explorer after media association metadata changes");
assert.ok(existsSync(linuxConfigUrl), "Linux desktop release builds must have a platform-specific Tauri config");
assert.equal(linuxConfig.bundle?.active, true, "Linux desktop release builds must produce native packages by default");
assert.deepEqual(linuxConfig.bundle?.targets, ["deb", "appimage"], "Linux desktop release build should target deb and AppImage packages");
assert.ok(linuxConfig.bundle?.icon?.includes("icons/128x128.png"), "Linux AppImage bundle must declare a square PNG icon");
assert.ok(linuxConfig.bundle?.linux?.deb?.depends?.includes("libmpv2"), "Linux deb packages must declare the libmpv runtime dependency");
assert.ok(linuxConfig.bundle?.linux?.deb?.depends?.includes("libwebkit2gtk-4.1-0"), "Linux deb packages must declare the WebKitGTK runtime dependency");
assert.ok(existsSync(macosConfigUrl), "macOS desktop release builds must have a platform-specific Tauri config");
assert.equal(macosConfig.identifier, "dev.openplayer.desktop", "macOS bundle identifier must not end with the .app extension");
assert.equal(macosConfig.bundle?.active, true, "macOS desktop release builds must produce native bundles by default");
assert.deepEqual(macosConfig.bundle?.targets, ["app", "dmg"], "macOS desktop release build should target app and DMG bundles");
assert.equal(config.app?.macOSPrivateApi, true, "macOS overlay builds must enable Tauri private APIs for transparent control windows");
assert.match(tauriCargoToml, /tauri\s*=\s*\{[^\n]*macos-private-api/, "Tauri's macos-private-api feature must be enabled for transparent macOS overlay windows");
assert.match(tauriCargoToml, /objc2-app-kit/, "macOS mpv embedding must use objc2 AppKit bindings");
assert.match(tauriBuildScript, /pkg-config[\s\S]*--libs-only-L[\s\S]*mpv/, "macOS mpv linking must read Homebrew lib paths from pkg-config");
assert.ok(existsSync(macosBundleScriptUrl), "macOS release builds must include a libmpv dylib bundling script");
assert.match(macosBundleScriptSource, /Contents\/Frameworks[\s\S]*otool[\s\S]*install_name_tool/, "macOS libmpv bundling must copy dylibs into Contents/Frameworks and rewrite install names");
assert.match(macosBundleScriptSource, /\.framework\/[\s\S]*cpSync/, "macOS libmpv bundling must include Homebrew framework dependencies such as Python.framework");
assert.match(config.build.devUrl, /23142$/, "Tauri dev URL must use the non-reserved Windows port");
assert.match(packageJson.scripts.dev, /23142$/, "Vite dev script must use the non-reserved Windows port");
assert.match(packageJson.scripts.preview, /23142$/, "Vite preview script must use the non-reserved Windows port");
assert.equal(packageJson.scripts["verify:release"], "node scripts/verify-release.mjs", "desktop package must expose release metadata verification");
assert.ok(existsSync(releaseVerifyScriptUrl), "release verification script must exist");
assert.ok(existsSync(releaseMpvManifestUrl), "Windows mpv dependency manifest must be tracked outside ignored vendor binaries");
assert.match(ciWorkflow, /npm run verify:release/, "CI must verify release metadata");
assert.match(ciWorkflow, /npm run verify:shell/, "CI must run shell structural verification");
assert.match(ciWorkflow, /FORCE_JAVASCRIPT_ACTIONS_TO_NODE24:\s*true/, "CI must opt into the GitHub Actions Node 24 runtime");
assert.doesNotMatch(`${ciWorkflow}\n${releaseWorkflow}`, /actions\/(?:checkout|setup-node)@v4/, "GitHub workflows must not use deprecated Node 20 action major versions");
assert.match(releaseWorkflow, /on:[\s\S]*tags:[\s\S]*v\*/, "release workflow must run for version tags");
assert.match(releaseWorkflow, /FORCE_JAVASCRIPT_ACTIONS_TO_NODE24:\s*true/, "release workflow must opt into the GitHub Actions Node 24 runtime");
assert.match(releaseWorkflow, /npm run tauri:build -- --config src-tauri\/tauri\.windows\.conf\.json/, "release workflow must build the Windows NSIS installer");
assert.match(releaseWorkflow, /mpv-windows-x64\.json/, "release workflow must restore mpv runtime from tracked dependency metadata");
assert.match(releaseWorkflow, /Get-FileHash[\s\S]*SHA256/, "release workflow must generate a SHA256 checksum for the installer");
assert.match(releaseWorkflow, /gh release/, "release workflow must publish installer assets to GitHub Releases");
assert.match(releaseWorkflow, /linux-packages:/, "release workflow must build Linux packages");
assert.match(releaseWorkflow, /runs-on:\s*ubuntu-latest/, "Linux release packages must build on Ubuntu runners");
assert.match(releaseWorkflow, /libmpv-dev/, "Linux release job must install libmpv development headers");
assert.match(releaseWorkflow, /libfuse2t64[\s\S]*libfuse2/, "Linux release job must handle the Ubuntu FUSE package rename for AppImage tooling");
assert.match(releaseWorkflow, /npm run tauri:build -- --config src-tauri\/tauri\.linux\.conf\.json/, "release workflow must build Linux deb and AppImage packages");
assert.match(releaseWorkflow, /target\/release\/bundle\/deb\/\*\.deb/, "release workflow must locate the Linux deb artifact");
assert.match(releaseWorkflow, /target\/release\/bundle\/appimage\/\*\.AppImage/, "release workflow must locate the Linux AppImage artifact");
assert.match(releaseWorkflow, /sha256sum[\s\S]*deb[\s\S]*sha256sum[\s\S]*appimage/, "release workflow must generate SHA256 checksums for Linux packages");
assert.match(releaseWorkflow, /gh release upload[\s\S]*OPENPLAYER_LINUX_DEB[\s\S]*OPENPLAYER_LINUX_APPIMAGE/, "release workflow must upload Linux packages and checksums to GitHub Releases");
assert.match(releaseWorkflow, /macos-packages:/, "release workflow must build unsigned macOS packages for internal testing");
assert.match(releaseWorkflow, /macos-15-intel/, "macOS release workflow must cover Intel runners explicitly");
assert.match(releaseWorkflow, /macos-15/, "macOS release workflow must cover Apple Silicon runners explicitly");
assert.match(releaseWorkflow, /brew install[\s\S]*mpv[\s\S]*pkg-config|brew install[\s\S]*pkg-config[\s\S]*mpv/, "macOS release job must install Homebrew mpv and pkg-config");
assert.match(releaseWorkflow, /npm run tauri:build -- --config src-tauri\/tauri\.macos\.conf\.json/, "release workflow must build macOS app and DMG bundles");
assert.match(releaseWorkflow, /bundle-macos-libmpv\.mjs/, "release workflow must bundle libmpv dylibs before packaging macOS DMGs");
assert.match(releaseWorkflow, /otool -L[\s\S]*\/opt\/homebrew[\s\S]*\/Cellar/, "release workflow must reject unbundled Homebrew dylib references in macOS packages");
assert.match(releaseWorkflow, /codesign --force --deep --sign -[\s\S]*OpenPlayer\.app/, "release workflow must re-sign the app bundle after rewriting macOS dylib references");
assert.match(releaseWorkflow, /target\/release\/bundle\/dmg\/\*\.dmg/, "release workflow must locate the macOS DMG artifact");
assert.match(releaseWorkflow, /shasum -a 256[\s\S]*dmg/, "release workflow must generate SHA256 checksums for macOS packages");
assert.match(indexHtml, /surface["')\s.]*={1,3}\s*"video"[\s\S]*surface-video/, "index.html must classify the main video surface before React mounts");
assert.match(indexHtml, /surface-overlay/, "index.html must classify non-video surfaces as transparent overlays before React mounts");
assert.match(indexHtml, /html\.surface-video[\s\S]*background:\s*#000/, "video surface must paint black before React and mpv finish loading");
assert.match(indexHtml, /html\.surface-overlay[\s\S]*background:\s*transparent/, "overlay surface must remain transparent before React mounts");
assert.ok(!existsSync(rootLogoUrl), "source logo must live under app assets, not the repository root");
assert.ok(existsSync(uiLogoUrl), "frontend logo asset must exist");
assert.ok(existsSync(tauriIconPngUrl), "Tauri PNG icon must exist");
assert.ok(existsSync(tauriIconIcoUrl), "Windows ICO icon must exist");
assert.ok(existsSync(tauriIconIcnsUrl), "macOS ICNS icon must exist");

assert.equal(packageJson.dependencies["movi-player"], undefined, "minimal branch must not ship WASM/software decoder dependency");
assert.ok(packageJson.dependencies["@tauri-apps/plugin-dialog"], "mpv path playback must use Tauri dialog to obtain real local paths");

assert.match(tauriCargoToml, /default = \["mpv-embed"\]/, "desktop default feature must use the stable mpv embed overlay backend");
assert.match(ciWorkflow, /libmpv-dev/, "Linux CI must install libmpv-dev so default mpv-embed tests can link libmpv");
assert.match(tauriCargoToml, /mpv-embed/, "Cargo features must define mpv-embed");
assert.doesNotMatch(tauriCargoToml, /mpv-render|Win32_Graphics_OpenGL/, "desktop crate must not keep the failed mpv render backend or its OpenGL render-only dependencies");
assert.match(tauriCargoToml, /libmpv2-sys/, "desktop crate must keep libmpv2-sys available for mpv_request_log_messages diagnostics");
assert.doesNotMatch(tauriBuildScript, /CARGO_FEATURE_MPV_RENDER/, "build script must not keep the removed mpv-render feature gate");
assert.match(tauriBuildScript, /CARGO_FEATURE_MPV_SMOKE[\s\S]*CARGO_FEATURE_MPV_EMBED/, "build script must only add mpv link paths when an mpv feature is enabled");
assert.match(tauriBuildScript, /vendor[\\/]native[\\/]mpv[\\/]windows-x64/, "build script must point at the vendored Windows mpv directory");
assert.match(tauriBuildScript, /macos_mpv_gl_view\.m[\s\S]*framework=OpenGL/, "macOS mpv render API host must compile the AppKit OpenGL child view and link OpenGL");
assert.match(tauriLibSource, /#\[cfg\(feature = "mpv-smoke"\)\]\s*mod mpv_smoke;/, "desktop crate must keep libmpv2 smoke code feature-gated");
assert.match(tauriLibSource, /#\[cfg\(feature = "mpv-embed"\)\]\s*mod mpv_embed;/, "desktop crate must compile the stable mpv child HWND backend behind mpv-embed");
assert.match(tauriLibSource, /mod platform_support;/, "desktop backend must expose platform capability metadata");
assert.match(tauriLibSource, /platform_support[\s\S]*history_list/, "desktop runtime must register platform support before persistence commands");
assert.match(platformSupportSource, /pub struct PlatformSupport/, "platform support module must define a serializable capability payload");
assert.match(platformSupportSource, /display_server:\s*&'static str/, "platform support must report the active native display server");
assert.match(platformSupportSource, /mpv_embed_video:\s*bool/, "platform support must report whether native mpv embedding is usable");
assert.match(platformSupportSource, /native_shortcut_bridge:\s*bool/, "platform support must report whether the native shortcut bridge is available");
assert.match(platformSupportSource, /WAYLAND_DISPLAY[\s\S]*GDK_BACKEND/, "platform support must distinguish Linux X11 and Wayland sessions");
assert.match(platformSupportSource, /prepare_platform_runtime[\s\S]*prepare_linux_runtime/, "platform support must prepare Linux runtime backend selection before Tauri starts");
assert.match(tauriLibSource, /prepare_platform_runtime\(\);[\s\S]*tauri::Builder::default/, "desktop runtime must prepare platform backend selection before building Tauri");
assert.doesNotMatch(tauriLibSource, /mpv_render|MpvRenderState|mpv_render_/, "desktop runtime must not reference the removed mpv render backend");
for (const fileUrl of mpvRenderFiles) {
  assert.ok(!existsSync(fileUrl), `removed render spike file must not exist: ${fileUrl.pathname}`);
}
assert.match(mpvEmbedRunSource, /pub\s+fn\s+run\s*\(\s*\)/, "desktop default runtime must include an mpv-embed run function");
assert.match(mpvEmbedRunSource, /WebviewWindowBuilder[\s\S]*surface=overlay/, "desktop runtime must create a separate transparent overlay controls window");
assert.match(mpvEmbedRunSource, /background_color\(Color\(0,\s*0,\s*0,\s*0\)\)/, "overlay window and webview must use an explicit transparent background to avoid compositor edge seams");
assert.match(mpvEmbedRunSource, /mpv_overlay_open_path/, "default runtime must register overlay commands that target the main video window");
assert.match(tauriLibSource, /mpv_overlay_open_path[\s\S]*main_window\(&app\)\?[\s\S]*mpv_embed::open_path_for_window\(&main, state\.inner\(\), path\)/, "overlay open command must target the main video window through mpv_embed");
assert.doesNotMatch(mpvEmbedRunSource, /\.always_on_top\(true\)/, "overlay controls must not be globally topmost over other apps");
assert.doesNotMatch(mpvEmbedRunSource, /\.position\(position\.x as f64, position\.y as f64\)|\.inner_size\(size\.width as f64, size\.height as f64\)/, "overlay startup must not pass physical main window pixels to logical builder sizing APIs");
assert.match(mpvEmbedRunSource, /\.visible\(false\)[\s\S]*sync_overlay_to_main\(&app_handle\)[\s\S]*overlay\.show\(\)/, "overlay startup must stay hidden until physical-position sync prevents DPI-scale misalignment");
assert.match(mpvEmbedRunSource, /WindowEvent::Resized[\s\S]*schedule_mpv_video_host_sync/, "main-window resize events must schedule delayed mpv host resyncs after WebView relayout");
assert.match(tauriLibSource, /#\[cfg\(all\(feature = "mpv-embed", windows\)\)\][\s\S]*SetWindowLongPtrW/, "overlay HWND ownership must be isolated to Windows mpv-embed builds");
assert.match(tauriLibSource, /#\[cfg\(all\(feature = "mpv-embed", not\(windows\)\)\)\][\s\S]*fn set_overlay_owner/, "non-Windows mpv-embed builds must not call Windows overlay ownership APIs");
assert.doesNotMatch(mpvEmbedRunSource, /OPENPLAYER_MPV_EMBED_FILE/, "normal embed overlay runtime must not auto-play the old Abbott embed smoke file");
assert.match(tauriLibSource, /tauri_plugin_dialog::init\(\)/, "desktop app must register Tauri dialog plugin for path-based mpv playback");
assert.ok(capability.permissions.includes("dialog:allow-open"), "capability must allow file-open dialog for path-based mpv playback");
assert.ok(capability.windows.includes("overlay"), "overlay controls window must be included in the dialog capability scope");
assert.doesNotMatch(appSource, /<video\b|URL\.createObjectURL/, "mpv-first player must not use browser video or object URLs");
assert.match(appSource, /surface=video|surface === "video"/, "frontend must render a video-only main surface separately from overlay controls");
assert.match(appSource, /open\(/, "player must keep native Tauri file picker access");
assert.match(appSource, /openplayer-logo\.png/, "empty player state must use the OpenPlayer logo asset");
assert.doesNotMatch(appSource, /MPV native playback/, "empty player state must not show the old playback engine tagline");
assert.match(appSource, /isPickerOpen/, "native file picker must guard against repeated open calls while the dialog is pending");
assert.match(appSource, /mpv_overlay_open_path/, "overlay controls must open files through commands targeting the main video window");
assert.match(appSource, /@tauri-apps\/plugin-dialog/, "frontend must use native dialog for mpv path selection");
assert.match(appSource, /openNativeMediaFiles/, "frontend must expose a picker-driven mpv open action");
assert.match(appSource, /type TimeDisplayMode\s*=\s*"timecode"\s*\|\s*"frames"/, "frontend must define a timecode/frame display mode");
assert.match(appSource, /type PlaybackClockAnchor/, "frontend must keep a display-clock anchor for smooth progress interpolation");
assert.match(appSource, /requestAnimationFrame/, "frontend must animate displayed progress with requestAnimationFrame");
assert.match(appSource, /anchorDisplayClock/, "frontend must reset the smooth display clock when mpv state changes");
assert.match(appSource, /formatTimecode/, "frontend must use adaptive timecode formatting");
assert.match(appSource, /formatFrameCount/, "frontend must format frame counts for frame mode");
assert.match(appSource, /toggleTimeDisplayMode/, "transport time labels must toggle timecode and frame display modes");
assert.match(appSource, /const displayTime\s*=\s*snapEndOfMediaPosition\(displayPosition/, "seek slider must use the interpolated display position");
assert.match(appSource, /Math\.floor\(displayTime \* framesPerSecond\)/, "current frame must be derived from smooth display time and fps");
assert.match(appSource, /Math\.floor\(duration \* framesPerSecond\)/, "total frame count must be derived from duration and fps");
assert.match(appSource, /fps:\s*number/, "frontend snapshot type must include fps metadata");
assert.match(appSource, /speed:\s*number/, "frontend snapshot type must include playback speed metadata");
assert.match(appSource, /subtitleDelay:\s*number/, "frontend snapshot type must include subtitle delay metadata");
assert.match(appSource, /type MpvTrack/, "frontend must define mpv track metadata for audio, video, and subtitles");
assert.match(appSource, /type PlatformSupport/, "frontend must define platform support metadata returned by the backend");
assert.match(appSource, /displayServer:\s*string/, "frontend platform support metadata must include display server details");
assert.match(appSource, /platformUnsupportedPlaybackMessage/, "frontend must render a friendly unsupported-platform playback message");
assert.match(appSource, /platformSupport[\s\S]*mpvEmbedVideo[\s\S]*openNativeMediaFiles/, "file opening must be gated when native mpv embedding is not supported on this platform");
assert.match(appSource, /type AppearanceState/, "frontend must define typed appearance state returned by redb-backed settings");
assert.match(appSource, /appearance_state/, "frontend must load appearance settings through the backend");
assert.match(appSource, /appearance_set_theme/, "frontend must select themes through the backend");
assert.match(appSource, /appearance_set_accent_override/, "frontend must persist accent overrides through the backend");
assert.match(appSource, /appearance_import_theme_plugin/, "frontend must import theme plugin manifests through the backend");
assert.match(appSource, /appearance_set_plugin_enabled/, "frontend must toggle theme plugins through the backend");
assert.match(appSource, /themeStyleVariables/, "frontend must apply theme tokens through CSS variables");
assert.match(appSource, /type PlayerPreferences/, "frontend must type persisted player preferences returned from redb-backed settings");
assert.match(appSource, /preferences_state/, "frontend must load player preferences through the backend");
assert.match(appSource, /preferences_set_incognito_mode/, "frontend must persist incognito mode through the backend");
assert.match(appSource, /preferences_set_quiet_keyboard_controls/, "frontend must persist quiet keyboard-control behavior through the backend");
assert.match(appSource, /resolveLocale\(playerPreferences\.languageMode,\s*browserLanguages\(\)\)/, "frontend must resolve display language from persisted language mode and browser/system languages");
assert.match(appSource, /translations\[locale\]/, "frontend must render through the active i18n translation bundle");
assert.match(appSource, /preferences_set_language_mode/, "frontend must persist manual language selection through the settings store");
assert.match(i18nSource, /export type AppLocale = "en-US" \| "zh-CN"/, "i18n layer must support English and Simplified Chinese locales");
assert.match(i18nSource, /startsWith\("zh"\)/, "i18n locale detection must map Chinese system languages to zh-CN");
assert.match(i18nSource, /mode === "system"[\s\S]*detectSystemLocale/, "i18n locale resolution must support automatic system language mode");
assert.match(i18nSource, /"en-US"[\s\S]*"zh-CN"/, "i18n translation resources must include both English and Chinese");
assert.match(appearanceStoreSource, /LANGUAGE_MODE_KEY/, "settings store must persist the language mode preference");
assert.match(appearanceStoreSource, /validate_language_mode[\s\S]*"system"[\s\S]*"en-US"[\s\S]*"zh-CN"/, "settings store must validate supported language modes");
assert.doesNotMatch(appSource, /OPENPLAYER_THEME_STORAGE_KEY|openplayer\.theme|localStorage\.(getItem|setItem)\([^)]*theme/i, "theme and plugin settings must not use frontend localStorage");
assert.match(appSource, /playbackSpeedOptions/, "frontend must expose curated playback speed choices");
assert.match(appSource, /mpv_embed_set_subtitle_delay/, "frontend must control mpv subtitle delay through a backend command");
assert.match(appSource, /subtitle-delay/, "media options panel must expose subtitle delay controls");
assert.doesNotMatch(appSource, /mpvSmoke|libmpv|libmpv2|mpv_smoke/, "libmpv2 smoke spike must not change the HTML video frontend path");
assert.doesNotMatch(appSource, /<video|videoRef|fileInputRef|type="file"|URL\.createObjectURL|URL\.revokeObjectURL|handleFileInputChange|onDrop=\{handleDrop\}/, "mpv-first player must not keep HTML video or browser File playback");
assert.match(appSource, /togglePlayback/, "player shell must wire play and pause behavior");
assert.match(appSource, /type ShortcutAction/, "player shell must define configurable shortcut actions");
assert.match(appSource, /defaultShortcutBindings/, "player shell must define default shortcut bindings");
assert.match(appSource, /OPENPLAYER_SHORTCUTS_STORAGE_KEY/, "shortcut settings must persist through localStorage");
assert.match(appSource, /openplayer\.shortcuts\.v3/, "shortcut storage version must reset stale D/F and fullscreen bindings");
assert.doesNotMatch(appSource, /openplayer\.shortcuts\.v2/, "shortcut storage must not keep the stale v2 bindings");
assert.match(appSource, /type PlaybackHistoryEntry/, "player shell must define typed playback history entries");
assert.match(appSource, /history_list/, "player shell must read persisted playback history through a backend command");
assert.match(appSource, /history_remember/, "player shell must write playback history through a backend command");
assert.match(appSource, /history_resume_position/, "player shell must resolve resume positions through a backend command");
assert.match(appSource, /history_clear/, "player shell must clear persisted playback history through a backend command");
assert.match(appSource, /resumePositionForPath/, "player shell must resume remembered playback positions when opening known paths");
assert.match(appSource, /rememberPlaybackProgress/, "player shell must remember progress from mpv snapshots");
assert.match(appSource, /playerPreferences\.incognitoMode[\s\S]*history_remember/, "incognito mode must prevent playback history writes");
assert.match(appSource, /RESUME_END_PROGRESS_RATIO/, "resume logic must use a duration-relative end threshold");
assert.match(appSource, /MIN_RESUME_PROGRESS_RATIO/, "resume logic must use a duration-relative start threshold");
assert.doesNotMatch(appSource, /OPENPLAYER_HISTORY_STORAGE_KEY|openplayer\.history\.v1|readPlaybackHistory|writePlaybackHistory|window\.localStorage\.setItem\(OPENPLAYER_HISTORY_STORAGE_KEY/, "playback history must not remain backed by frontend localStorage");
assert.match(appSource, /keyboardEventToChord/, "shortcut settings must normalize keyboard events into configurable chords");
assert.match(appSource, /performShortcutAction/, "global shortcut dispatch must route configured chords to player commands");
assert.match(appSource, /recordingShortcutAction/, "settings must support recording a replacement shortcut chord");
assert.match(appSource, /shortcutKeyDownRef/, "global keydown dispatch must use a stable ref so playback progress animation does not reinstall shortcut listeners");
assert.match(appSource, /window\.addEventListener\("keydown",\s*handleGlobalKeyDown,\s*\{\s*capture:\s*true\s*\}\);\s*return[\s\S]*window\.removeEventListener\("keydown",\s*handleGlobalKeyDown,\s*\{\s*capture:\s*true\s*\}\);\s*},\s*\[\]\)/, "global keydown listener must be installed once and read current state through refs");
assert.match(appSource, /openplayer-native-shortcut/, "frontend must listen for native shortcut events when the overlay webview is not focused");
assert.match(appSource, /window_update_shortcuts/, "frontend must mirror custom shortcut bindings to the native shortcut bridge");
assert.match(appSource, /window_set_shortcuts_enabled/, "frontend must disable native shortcut dispatch while menus or shortcut capture are active");
assert.match(appSource, /frameForward/, "player shell must define a configurable forward-one-frame shortcut action");
assert.match(appSource, /frameBackward/, "player shell must define a configurable backward-one-frame shortcut action");
assert.match(appSource, /toggleFullscreen:\s*"Enter"/, "fullscreen shortcut must default to Enter");
assert.match(appSource, /frameBackward:\s*"D"/, "backward-one-frame shortcut must default to D");
assert.match(appSource, /frameForward:\s*"F"/, "forward-one-frame shortcut must default to F");
assert.match(appSource, /mpv_embed_frame_step/, "forward-one-frame shortcut must use mpv frame-step");
assert.match(appSource, /mpv_embed_frame_back_step/, "backward-one-frame shortcut must use mpv frame-back-step");
assert.doesNotMatch(appSource, /audioVisualizerColor/, "audio visualization must use app theme CSS variables instead of passing accent colors into mpv");
assert.match(appSource, /mpv_embed_set_speed/, "frontend must control mpv playback speed through a backend command");
assert.match(appSource, /mpv_embed_set_hwdec/, "frontend must control mpv hardware decoding mode through a backend command");
assert.match(appSource, /mpv_embed_set_video_fill/, "frontend must expose mpv video fill as an explicit media option instead of changing it during fullscreen");
assert.match(appSource, /decode-toggle/, "control strip must replace the prominent settings button with the decode-mode toggle");
assert.doesNotMatch(appSource, /aria-label="Open settings"/, "settings must remain available through the context menu instead of the bottom control strip");
assert.match(appSource, /mpv_embed_select_track/, "frontend must switch audio, video, and subtitle tracks through a backend command");
assert.match(appSource, /mpv_embed_add_subtitle/, "frontend must load external subtitle files through mpv");
assert.match(appSource, /mpv_embed_stop/, "frontend must expose mpv stop playback control");
assert.doesNotMatch(appSource, /closest\([^)]*button|role='button'/, "global shortcuts must not be disabled just because a player button is focused");
assert.match(appSource, /isTextEntryShortcutTarget/, "global shortcut filtering must only suppress text-entry targets");
assert.match(appSource, /TEXT_ENTRY_INPUT_TYPES/, "global shortcut filtering must not suppress range sliders or player buttons");
assert.match(appSource, /releaseShortcutFocusTarget/, "global shortcuts must release non-text control focus before dispatching player actions");
assert.match(appSource, /window_focus_overlay/, "frontend must be able to restore overlay focus after native dialogs or window commands");
assert.match(appSource, /context-menu/, "overlay must render a custom right-click context menu");
assert.match(appSource, /settings-dialog/, "overlay must render a settings dialog for player preferences");
assert.match(appSource, /onContextMenu=\{openContextMenu\}/, "player surface must open the custom context menu on right click");
assert.match(appSource, /window_toggle_fullscreen/, "overlay UI must route fullscreen through a backend command targeting the main video window");
assert.doesNotMatch(appSource, /getCurrentWindow\(\)[\s\S]*setFullscreen/, "overlay UI must not fullscreen the overlay window itself");
assert.match(appSource, /event\.button\s*===\s*1[\s\S]*window_toggle_fullscreen/, "non-control surface must toggle fullscreen with the middle mouse button");
assert.match(appSource, /onDoubleClick=\{handleDragRegionDoubleClick\}/, "non-control surface must toggle play and pause with double click");
assert.doesNotMatch(appSource, /data-tauri-drag-region/, "full-surface video interaction layer must not use Tauri's automatic drag region because it swallows double-click playback toggles");
assert.match(appSource, /WINDOW_DRAG_START_DISTANCE_PX[\s\S]*handleDragRegionPointerMove[\s\S]*startMainWindowDrag/, "video-surface drag must start from pointer movement threshold instead of a timer so dragging remains responsive while double-click works");
assert.doesNotMatch(appSource, /dragStartTimerRef|setTimeout\(\(\) => \{\s*[^}]*startMainWindowDrag/, "video-surface drag must not wait on a double-click delay timer");
assert.match(appSource, /window_apply_resize_delta/, "macOS overlay resize handles must use a manual resize delta fallback because tao does not support drag_resize_window on macOS");
assert.match(appSource, /platformSupport\?\.os\s*===\s*"macos"[\s\S]*manualResizeDragRef/, "macOS resize handles must select the manual resize path only on macOS");
assert.match(appSource, /setPointerCapture[\s\S]*manualResizeDragRef|manualResizeDragRef[\s\S]*setPointerCapture/, "manual macOS resize fallback must capture pointer movement until release");
assert.match(appSource, /requestManualResizeFlush[\s\S]*resizeCommandInFlight/, "manual macOS resize fallback must coalesce pointer deltas and keep only one resize IPC in flight");
assert.match(appSource, /flushManualResizeDelta[\s\S]*applyManualMainWindowResize/, "manual macOS resize fallback must flush coalesced deltas through the backend resize command");
assert.match(appSource, /window_set_resize_cursor/, "resize handles must explicitly set native cursor icons instead of relying only on CSS over transparent macOS overlays");
assert.match(appSource, /onPointerEnter=\{\(event\) => handleResizePointerEnter\(event, region\.direction\)\}/, "resize handles must set the matching cursor as soon as the pointer enters the hit area");
assert.match(appSource, /onPointerLeave=\{handleResizePointerLeave\}/, "resize handles must restore the default cursor when the pointer leaves the hit area");
assert.match(appSource, /resizeFeedback/, "resize handles must maintain visible in-app resize feedback state for macOS when native cursor icons are unavailable");
assert.match(appSource, /resize-feedback--active/, "resize dragging must strengthen the in-app resize feedback");
assert.match(appSource, /resize-feedback--/, "player shell must render a direction-specific resize feedback layer");
assert.match(appSource, /handleResizePointerEnd[\s\S]*setNativeResizeCursor\(null\)[\s\S]*setResizeBoundaryFeedback\(null\)/, "resize feedback must disappear immediately when resize dragging ends instead of falling back to hover state");
assert.match(appSource, /videoLayout[\s\S]*video-layout-options[\s\S]*setVideoFillMode/, "video fill/crop must live with the track and subtitle media options");
assert.match(appSource, /onWheel=\{handleShellWheel\}/, "player shell must support mouse wheel volume control");
assert.match(appSource, /volumeFeedback/, "volume changes from wheel and shortcuts must display a transient volume overlay");
assert.doesNotMatch(appSource, /volume-feedback-track/, "volume feedback overlay must stay compact and not render a progress track");
assert.match(appSource, /accent-picker-preview/, "custom accent picker must render its own clean color preview swatch");
assert.match(appSource, /preference-switch/, "playback preferences must use custom switch controls instead of raw checkboxes");
assert.match(appSource, /recordShortcutActivity/, "keyboard shortcuts must decide whether to reveal chrome per action and preference");
assert.match(appSource, /quietKeyboardControls[\s\S]*seekBackward[\s\S]*volumeUp/, "quiet keyboard controls must keep seek and volume shortcuts from revealing chrome");
assert.doesNotMatch(appSource, /video\.play\(\)|video\.pause\(\)|video\.currentTime|videoRef\.current\.volume|advanceToNextQueueItem|pendingAutoplayRef/, "controls must not call HTML video APIs");

assert.doesNotMatch(appSource, /convertFileSrc/, "frontend must not use asset URLs or old native preview plumbing");
assert.doesNotMatch(appSource, /PlaybackSourceDto|PlaybackSnapshotDto|runPlaybackCommand|mirrorPlaybackCommand|storage_|recentMedia|PlaybackProgressDto/, "frontend must not keep backend playback, storage, recent, or progress plumbing");
assert.doesNotMatch(appSource, /movi-player|MoviPlayer|moviEventLog/, "frontend must not include Movi playback code");

assert.match(appSource, /playlist-drawer/, "playlist must remain a collapsible drawer");
assert.match(appSource, /togglePlaylist/, "control bar must keep playlist toggle");
assert.match(appSource, /appendNativeMediaFiles/, "playlist must support adding multiple selected files without replacing the queue");
assert.match(appSource, /appendNativeMediaFolder[\s\S]*media_files_in_directory/, "playlist must support adding a selected folder through the backend media scanner");
assert.match(appSource, /startup_media_paths[\s\S]*replaceQueueWithMediaPaths/, "frontend must open media paths passed by Windows file association startup");
assert.match(appSource, /clearPlaybackHistory/, "playlist and settings must expose playback history clearing");
assert.match(appSource, /shell_preview_formats/, "settings must load selectable Windows Explorer preview formats");
assert.match(appSource, /shell_preview_register_formats/, "settings must register only the Explorer preview formats selected by the user");
assert.match(appSource, /shell_preview_open_default_apps_settings/, "settings must provide a Windows default-app settings shortcut");
assert.match(appSource, /shell-preview-format--unselected/, "Explorer preview format buttons must explicitly mark unselected state");
assert.match(appSource, /toggleAllShellPreviewFormats/, "settings must expose a select-all and clear-all preview format toggle");
assert.match(appSource, /resetShellPreviewFormatsToDefault/, "settings must expose a default preview format selection action");
assert.doesNotMatch(appSource, /shell_preview_register_all/, "settings must not register every Explorer preview format without user selection");
assert.match(appSource, /shellPreviewRegistrationStatus/, "settings must report Explorer preview registration results inline");
assert.match(appSource, /history-section/, "playlist drawer must expose local playback history");
assert.match(appSource, /openHistoryEntry/, "playback history entries must reopen media paths");
assert.match(appSource, /playPreviousQueueItem[\s\S]*playNextQueueItem/, "timeline must expose previous and next queue navigation");
assert.match(appSource, /stopPlayback/, "control strip must expose a stop playback command");
assert.match(appSource, /type LoopMode\s*=\s*"off"\s*\|\s*"one"\s*\|\s*"all"/, "player shell must model loop mode options");
assert.match(appSource, /mediaPanelMode === "loop"[\s\S]*loop-option/, "restart-side control must open a loop-mode panel instead of only seeking to start");
assert.match(appSource, /loadedMediaPath[\s\S]*mpv_embed_set_loop_file/, "loop-mode synchronization must wait until mpv has actually loaded the selected media");
assert.match(appSource, /loadedMediaPath !== media\.path[\s\S]*mpv_embed_set_loop_file/, "opening media must not show a transient no-loaded-media warning from loop-mode synchronization");
assert.match(appSource, /window_start_drag/, "overlay drag region must ask the backend to drag the main video window");
assert.doesNotMatch(appSource, /onDoubleClick=\{toggleFullscreen\}/, "fullscreen must use middle mouse button instead of double-click");
assert.match(appSource, /window_start_resize/, "overlay resize handles must ask the backend to resize the main video window");
assert.match(appSource, /pendingSeek/, "seek UI must track pending seek targets to prevent stale snapshot rollback");
assert.match(appSource, /SEEK_CONFIRM_TOLERANCE_SECONDS/, "seek UI must define a tolerance for mpv seek confirmation");
assert.match(appSource, /SEEK_SNAPSHOT_SUPPRESS_MS/, "seek UI must bound stale snapshot suppression while mpv catches up");
assert.match(appSource, /AUTO_HIDE_CONTROLS_MS\s*=\s*5000/, "overlay chrome must hide after 5 seconds of no user activity");
assert.match(appSource, /stage--chrome-hidden/, "overlay must apply a hidden chrome class after inactivity");
assert.match(appSource, /onPointerMove=\{recordUserActivity\}/, "overlay must reveal controls on pointer movement");
assert.match(appSource, /handleShellPointerLeave/, "overlay must hide player chrome when the pointer leaves the window");
assert.match(appSource, /onPointerLeave=\{handleShellPointerLeave\}/, "player shell must listen for pointer leave to hide inactive chrome");
assert.match(appSource, /isChromePinned/, "overlay must pin controls while dialogs, errors, or drawers are active");
assert.match(appSource, /snapshot\.status\s*===\s*"playing"/, "frontend must only animate the display clock for explicit playing snapshots");
assert.doesNotMatch(appSource, /snapshot\.status\s*!==\s*"idle"\s*&&\s*snapshot\.status\s*!==\s*"ended"/, "frontend must not treat paused frame-step snapshots as playing");
assert.match(appSource, /END_OF_MEDIA_SNAP_TOLERANCE_SECONDS/, "frontend must define a near-end snap tolerance for the visible slider value");
assert.match(appSource, /snapEndOfMediaPosition/, "frontend must snap visible end-of-media slider value to duration");
assert.match(appSource, /const displayTime\s*=\s*snapEndOfMediaPosition/, "frontend must derive a snapped display time for labels, progress, and range value");
assert.match(appSource, /value=\{displayTime\}/, "seek slider thumb must use the snapped display time, not raw currentTime");
assert.match(appSource, /className="seek-slider"[\s\S]*step="any"/, "seek slider must use step=any so short clip durations can render exactly at max");
assert.match(appSource, /className="seek-control"[\s\S]*--progress/, "seek UI must expose a stable progress wrapper for smooth visual fill");
assert.match(appSource, /className="seek-progress"/, "seek UI must render an independent progress fill instead of relying only on native range background repainting");
assert.match(appSource, /--progress-ratio/, "seek UI must expose a unitless progress ratio for exact custom thumb positioning");
assert.match(appSource, /className="seek-thumb"/, "seek UI must render its own thumb instead of relying on WebView range pseudo-element alignment");
assert.doesNotMatch(dragRegionSources, /setPointerCapture|releasePointerCapture|startDragging|DragIntent|continueWindowDragIntent|beginWindowDragIntent/, "custom chrome drag regions must not use a pointer-capture startDragging loop that freezes render windows");
assert.doesNotMatch(appSource, /titlebar-brand|titlebar-center|side-rail|status-line/, "confirmed baseline UI must not regress to the older chrome layout");

assert.match(styles, /\.window-shell[\s\S]*border:\s*0/, "window shell must not draw an outer border");
assert.match(styles, /\.app-shell[\s\S]*padding:\s*0/, "window shell must not leave a transparent outer gutter");
assert.match(styles, /\.window-controls button\s*\{[\s\S]*color:\s*var\(--accent\)/, "window control icons must follow the selected accent color");
assert.match(styles, /\.window-controls\s*\{[^}]*right:\s*24px/, "window controls must align horizontally with the bottom transport inset");
assert.match(styles, /\.volume-feedback\s*\{[^}]*left:\s*24px/, "volume feedback must align horizontally with the bottom transport inset");
assert.doesNotMatch(styles, /\.recent-shortcuts|\.recent-drawer-section|\.status-line/, "minimal UI must not keep recent-media or status chrome styles");
assert.match(styles, /playlist-item--active/, "playlist styles must mark the active queue item");
assert.match(styles, /\.history-section/, "styles must include playback history section styling");
assert.match(styles, /\.history-item/, "styles must include playback history item styling");
assert.match(styles, /\.drag-region\s*\{[\s\S]*inset:\s*0/, "drag region must cover the non-control player surface, not just the title strip");
assert.match(styles, /\.resize-region\s*\{[\s\S]*z-index:\s*95/, "overlay must keep resize hit areas above modal backdrops");
assert.match(styles, /\.resize-region--south-east/, "overlay must include corner resize hit areas");
assert.match(styles, /\.resize-feedback\s*\{[\s\S]*pointer-events:\s*none/, "resize feedback must be visible without blocking media controls or resize hit areas");
assert.match(styles, /\.resize-feedback\s*\{[\s\S]*z-index:\s*96/, "resize feedback must render above transparent resize hit areas so edge hints are complete");
assert.match(styles, /\.resize-feedback--north[\s\S]*\.resize-feedback-line--north/, "resize feedback must show a top edge hint");
assert.match(styles, /\.resize-feedback--south-east[\s\S]*\.resize-feedback-corner--south-east/, "resize feedback must show a corner hint");
assert.match(styles, /\.transport\s*\{[\s\S]*pointer-events:\s*auto/, "transport controls must remain interactive above the full-surface drag region");
assert.match(styles, /\.playlist-drawer--open\s*\{[\s\S]*pointer-events:\s*auto/, "open playlist drawer must remain interactive above the full-surface drag region");
assert.match(styles, /\.empty-open-logo/, "empty player state must style the OpenPlayer logo");
assert.match(styles, /\.empty-open\s*\{[\s\S]*justify-items:\s*center/, "empty player state must center each logo and text item");
assert.match(styles, /\.stage--chrome-hidden[\s\S]*\.window-controls[\s\S]*opacity:\s*0/, "inactive player chrome must hide window controls");
assert.match(styles, /\.stage--chrome-hidden[\s\S]*\.transport[\s\S]*pointer-events:\s*none/, "inactive player chrome must hide and disable transport controls");
assert.match(styles, /\.context-menu/, "styles must include the custom context menu");
assert.match(styles, /\.settings-dialog/, "styles must include the settings dialog");
assert.match(styles, /--accent-soft/, "styles must expose theme-driven accent softness variables");
assert.match(styles, /\.theme-grid/, "styles must include theme selection grid styling");
assert.match(styles, /\.theme-card/, "styles must include theme card styling");
assert.match(styles, /\.accent-swatches/, "styles must include accent swatch styling");
assert.match(styles, /\.accent-picker/, "styles must include a custom accent color picker");
assert.match(styles, /\.accent-picker-preview/, "custom accent picker must style a clean preview swatch");
assert.match(styles, /\.plugin-list/, "styles must include theme plugin list styling");
assert.match(styles, /\.language-options/, "styles must include language selection controls");
assert.match(appSource, /type MediaPanelMode\s*=\s*"speed"\s*\|\s*"tracks"\s*\|\s*"loop"/, "frontend must model speed, track, and loop controls as separate media panel modes");
assert.match(appSource, /mediaPanelMode === "speed"[\s\S]*className="media-panel media-panel--speed"[\s\S]*t\.media\.speed/, "speed panel must only own playback speed controls through localized copy");
assert.match(appSource, /mediaPanelMode === "tracks"[\s\S]*className="media-panel media-panel--tracks"[\s\S]*renderTrackList\("audio"[\s\S]*renderTrackList\("video"[\s\S]*renderTrackList\("subtitle"/, "track and subtitle controls must live in their own panel");
assert.doesNotMatch(appSource, /aria-label="Playback speed and track options"/, "speed controls must not be labeled as the combined track/subtitle panel");
assert.match(styles, /\.media-panel\s*\{[\s\S]*right:\s*24px[\s\S]*bottom:\s*124px/, "media panels must align to the transport right edge and sit above the controls");
assert.match(styles, /\.media-panel--speed\s*\{[\s\S]*width:\s*min\(360px,\s*calc\(100vw - 48px\)\)/, "speed panel must stay compact so it does not overrun the transport controls");
assert.match(styles, /\.media-panel--tracks\s*\{[\s\S]*width:\s*min\(420px,\s*calc\(100vw - 48px\)\)/, "track panel must have its own bounded width");
assert.match(styles, /\.transport-time\s*\{[\s\S]*color:\s*var\(--accent\)/, "transport time labels must follow the selected accent color");
assert.match(styles, /\.control-strip button\s*\{[\s\S]*color:\s*var\(--accent\)/, "bottom control icons must follow the selected accent color");
assert.match(styles, /\.volume-control\s*\{[\s\S]*color:\s*var\(--accent\)/, "volume icon must follow the selected accent color");
assert.match(styles, /\.timeline-step-button/, "timeline must style compact previous and next controls beside the seek rail");
assert.match(styles, /\.volume-feedback/, "styles must include the transient volume percentage overlay");
assert.match(styles, /\.shell-preview-card/, "settings must style Explorer preview registration as a dedicated action card");
assert.match(appSource, /className="shell-preview-action"/, "Explorer preview card action buttons must use a targeted class instead of styling every nested button");
assert.doesNotMatch(styles, /\.shell-preview-card button[\s\S]*\.shell-preview-format/, "Explorer preview card action button rules must not override selectable format states");
assert.match(styles, /\.shell-preview-format--unselected\s*\{[\s\S]*background:\s*#171a1d[\s\S]*opacity:\s*0\.62/, "unselected Explorer preview formats must be visibly neutral gray instead of theme-colored");
assert.match(styles, /\.shell-preview-format--selected::after[\s\S]*background:\s*var\(--accent\)/, "selected Explorer preview formats must render a visible accent selection marker");
assert.doesNotMatch(appSource, /format\.common\s*&&\s*<small>常用<\/small>/, "Explorer preview format buttons must not render common badges that obscure extension names");
assert.match(styles, /\.audio-visualizer/, "styles must include the audio-only visualization surface");
assert.match(appSource, /audio-visualizer--paused/, "audio visualization must freeze its lightweight motion while playback is paused");
assert.match(appSource, /audio-visualizer-bars/, "audio visualization must render the lightweight app-layer bar effect");
assert.match(styles, /@keyframes audio-bar-float/, "audio visualization must use the earlier lightweight bar animation");
assert.match(styles, /\.audio-visualizer--paused[\s\S]*animation-play-state:\s*paused/, "paused audio visualization must hold the current visual frame");
assert.match(styles, /\.audio-visualizer-bars span[\s\S]*var\(--accent\)/, "audio visualization bars must follow the selected app theme accent");
assert.match(mpvEmbedSource, /configure_audio_visualizer/, "mpv embed must keep audio-only cover art disabled for the app-layer visualizer");
assert.doesNotMatch(mpvEmbedSource, /showwaves|showcqt|lavfi-complex/, "mpv embed must not render the rejected native waveform or frequency visualizer");
assert.doesNotMatch(styles, /\.volume-feedback-track/, "volume feedback must not include a heavy progress track");
assert.match(appSource, /className="open-media-button"/, "open-media control must have a targeted class for optical icon alignment");
assert.match(styles, /\.open-media-button\s+\.icon[\s\S]*translateY\(-1px\)/, "open-media folder icon must be optically centered with neighboring controls");
assert.match(styles, /\.preference-switch/, "playback settings must style checkbox preferences as switches");
assert.match(styles, /\.loop-option/, "styles must include loop mode option controls");
assert.doesNotMatch(styles, /border-color:\s*rgba\(202,\s*160,\s*93,\s*0\.42\)/, "interactive media panel borders must use theme accent variables instead of the default accent literal");
assert.match(styles, /\.media-panel/, "styles must include media option panels");
assert.match(styles, /\.track-list/, "styles must include track list controls");
assert.match(styles, /\.shortcut-row/, "styles must include shortcut editor rows");
assert.match(styles, /\.seek-control/, "styles must include a seek progress wrapper");
assert.match(styles, /--seek-thumb-size:\s*13px/, "seek control must define the thumb size used for rail alignment");
assert.match(styles, /\.seek-rail[\s\S]*left:\s*calc\(var\(--seek-thumb-size\) \/ 2\)[\s\S]*right:\s*calc\(var\(--seek-thumb-size\) \/ 2\)/, "seek rail must start under the thumb center so frame 0 aligns with the rail origin");
assert.match(styles, /\.seek-rail[\s\S]*top:\s*50%[\s\S]*transform:\s*translateY\(-50%\)/, "seek rail must be vertically centered with the range thumb");
assert.match(styles, /\.seek-progress[\s\S]*width:\s*var\(--progress\)/, "seek progress fill must be driven by the smooth display position");
assert.match(styles, /\.seek-thumb[\s\S]*top:\s*50%[\s\S]*left:\s*calc\(\(var\(--seek-thumb-size\) \/ 2\) \+ \(\(100% - var\(--seek-thumb-size\)\) \* var\(--progress-ratio\)\)\)[\s\S]*transform:\s*translate\(-50%,\s*-50%\)/, "custom seek thumb must share the rail coordinate system and be vertically centered");
assert.match(styles, /\.seek-slider::-webkit-slider-thumb[\s\S]*opacity:\s*0/, "native WebKit range thumb must be hidden so WebView pseudo-element alignment cannot shift the visible thumb");
assert.match(styles, /\.seek-slider::-moz-range-thumb[\s\S]*opacity:\s*0/, "native Firefox range thumb must be hidden so the custom thumb is the only visible marker");
assert.match(styles, /:focus-visible/, "interactive overlays must keep visible keyboard focus states");

assert.match(mpvEmbedSource, /get_property::<bool>\("eof-reached"\)/, "mpv snapshots must read eof-reached to identify true playback end");
assert.match(mpvEmbedSource, /wait_event\(0\.0\)/, "mpv snapshots must drain the event queue without blocking");
assert.match(mpvEmbedSource, /Event::EndFile\(mpv_end_file_reason::Eof\)/, "mpv snapshots must track the real EndFile EOF event");
assert.match(mpvEmbedSource, /prepare_libmpv_numeric_locale/, "mpv embed backend must prepare C numeric locale before mpv_create");
assert.match(mpvEmbedSource, /setlocale[\s\S]*LC_NUMERIC[\s\S]*"C"|"C"[\s\S]*setlocale[\s\S]*LC_NUMERIC/, "mpv embed backend must set LC_NUMERIC=C before libmpv initialization");
assert.match(mpvEmbedSource, /configure_native_video_output/, "mpv embed backend must configure platform video output before mpv_initialize");
assert.match(mpvEmbedSource, /OPENPLAYER_MPV_VO/, "Linux mpv embedding must allow OPENPLAYER_MPV_VO overrides for field diagnostics");
assert.match(mpvEmbedSource, /mpv_request_log_messages/, "mpv embed backend must subscribe to mpv logs for Linux video-output diagnostics");
assert.match(mpvEmbedSource, /Event::LogMessage[\s\S]*is_mpv_video_diagnostic_log/, "mpv embed backend must filter and forward mpv video-output diagnostic logs");
assert.match(mpvEmbedSource, /has_linux_dri_render_node/, "Linux mpv embedding must detect missing DRI render nodes before choosing GPU output");
assert.match(mpvEmbedSource, /is_virtual_linux_drm_driver/, "Linux mpv embedding must detect virtual DRM drivers before choosing GPU output");
assert.match(mpvEmbedSource, /vo:\s*Some\("x11"[\s\S]*hwdec:\s*"no"/, "Linux mpv embedding must fall back to vo=x11 and hwdec=no for software or virtual display stacks");
assert.match(mpvEmbedSource, /gpu_context:\s*Some\("x11egl"[\s\S]*hwdec:\s*"auto-safe"/, "Linux mpv embedding should use x11egl only for GPU-capable X11 stacks");
assert.match(mpvEmbedSource, /set_option\("vo",\s*vo\.as_str\(\)\)/, "mpv embed backend must apply the selected video output dynamically");
assert.doesNotMatch(mpvEmbedSource, /set_option\("gpu-context",\s*"x11egl"\)/, "Linux mpv embedding must not unconditionally force x11egl on virtual display stacks");
assert.match(mpvEmbedSource, /get_property::<f64>\("percent-pos"\)/, "mpv snapshots must read percent-pos for near-final-frame detection");
assert.match(mpvEmbedSource, /END_OF_MEDIA_SNAP_TOLERANCE_SECONDS/, "mpv snapshots must define a near-end snap tolerance");
assert.match(mpvEmbedSource, /position:\s*if \(ended \|\| near_end\)[\s\S]*duration/, "mpv snapshots must clamp end-of-file position to duration");
assert.match(mpvEmbedSource, /if ended \{\s*"ended"/, "mpv snapshots must expose ended status at EOF");
assert.match(mpvEmbedSource, /fps:\s*f64/, "mpv snapshots must serialize fps metadata");
assert.match(mpvEmbedSource, /speed:\s*f64/, "mpv snapshots must serialize playback speed");
assert.match(mpvEmbedSource, /subtitle_delay:\s*f64/, "mpv snapshots must serialize subtitle delay");
assert.match(mpvEmbedSource, /pub struct MpvEmbedTrack/, "mpv snapshots must serialize track metadata");
assert.match(mpvEmbedSource, /container-fps/, "mpv snapshots must prefer container-fps for frame-count mode");
assert.match(mpvEmbedSource, /estimated-vf-fps/, "mpv snapshots must fall back to estimated-vf-fps when container fps is unavailable");
assert.match(mpvEmbedSource, /mpv_embed_frame_step/, "mpv embed backend must expose a forward-one-frame command");
assert.match(mpvEmbedSource, /mpv_embed_frame_back_step/, "mpv embed backend must expose a backward-one-frame command");
assert.match(mpvEmbedSource, /mpv_embed_set_speed/, "mpv embed backend must expose playback speed control");
assert.match(mpvEmbedSource, /mpv_embed_set_hwdec[\s\S]*set_property\("hwdec"/, "mpv embed backend must expose runtime hardware/software decoding control");
assert.match(mpvEmbedSource, /normalize_hwdec_mode[\s\S]*"hardware"[\s\S]*"software"/, "mpv embed backend must normalize decode modes to safe mpv hwdec values");
assert.match(mpvEmbedSource, /mpv_embed_set_loop_file[\s\S]*set_property\("loop-file"/, "mpv embed backend must expose native single-file loop control");
assert.match(mpvEmbedSource, /mpv_embed_set_subtitle_delay/, "mpv embed backend must expose subtitle delay control");
assert.match(mpvEmbedSource, /mpv_embed_select_track/, "mpv embed backend must expose track selection");
assert.match(mpvEmbedSource, /mpv_embed_add_subtitle/, "mpv embed backend must expose external subtitle loading");
assert.match(mpvEmbedSource, /"frame-step"/, "mpv embed backend must call mpv frame-step for forward frame stepping");
assert.match(mpvEmbedSource, /"frame-back-step"/, "mpv embed backend must call mpv frame-back-step for backward frame stepping");
assert.match(mpvEmbedSource, /track-list\/count/, "mpv embed backend must read mpv track-list metadata");
assert.match(mpvEmbedSource, /sub-add/, "mpv embed backend must use mpv sub-add for external subtitles");
assert.match(mpvEmbedSource, /discover_sidecar_subtitles/, "mpv embed backend must discover same-folder sidecar subtitles when opening media");
assert.match(mpvEmbedSource, /"sub-delay"/, "mpv embed backend must control mpv sub-delay for subtitle sync");
assert.match(mpvEmbedSource, /#\[cfg\(windows\)\][\s\S]*use windows_sys::Win32/, "mpv native video host must keep Win32 imports behind a Windows platform gate");
assert.match(mpvEmbedSource, /SetWindowPos[\s\S]*HWND_TOP[\s\S]*SWP_NOACTIVATE[\s\S]*SWP_SHOWWINDOW/, "Windows mpv child window resizes must reassert top child z-order over the black WebView video surface");
assert.match(mpvEmbedSource, /RawWindowHandle::Xlib[\s\S]*RawWindowHandle::Xcb/, "mpv native video host must support X11 window ids on Linux");
assert.match(mpvEmbedSource, /Wayland[\s\S]*not implemented yet/, "mpv native video host must explicitly reject Wayland until a separate host path exists");
assert.match(mpvEmbedSource, /RawWindowHandle::AppKit[\s\S]*ns_view/, "mpv native video host must support AppKit NSView ids on macOS");
assert.match(mpvEmbedSource, /openplayer_mpv_gl_view_create[\s\S]*create_macos_render_context/, "macOS mpv embedding must create an AppKit render view before wiring libmpv rendering");
assert.match(mpvEmbedSource, /mpv_render_context_create[\s\S]*mpv_render_context_set_update_callback/, "macOS mpv embedding must use libmpv's render API instead of relying on unsupported --wid window nesting");
assert.match(mpvEmbedSource, /openplayer_mpv_gl_view_resize/, "macOS mpv render view must resize with the Tauri video host");
assert.match(mpvEmbedSource, /#\[cfg\(target_os = "macos"\)\]\s*fn platform_video_output_config[\s\S]*vo:\s*Some\("libmpv"\.to_string\(\)\)/, "macOS mpv embedding must use vo=libmpv so mpv does not create its own Cocoa window");
assert.match(mpvEmbedSource, /#\[cfg\(target_os = "macos"\)\][\s\S]*video-timing-offset"[\s\S]*"0"/, "macOS libmpv render path must avoid blocking AppKit on mpv frame timing");
assert.match(macosGlViewSource, /NSOpenGLView[\s\S]*MPV_RENDER_PARAM_OPENGL_FBO[\s\S]*mpv_render_context_render/, "macOS AppKit host must render libmpv frames into an OpenGL child view");
assert.match(macosGlViewSource, /dispatch_async\(dispatch_get_main_queue\(\)/, "macOS mpv render updates must schedule drawing on the AppKit main thread");
assert.doesNotMatch(macosGlViewSource, /\[[^\]]+\s+display(?:IfNeeded)?\]/, "macOS mpv render update callbacks must not synchronously render on the AppKit main thread");
assert.match(macosGlViewSource, /renderScheduled[\s\S]*setNeedsDisplay:YES/, "macOS mpv render updates must be coalesced into asynchronous redraw requests");
assert.match(mpvEmbedSource, /async fn mpv_embed_play[\s\S]*run_mpv_command/, "macOS mpv play commands must run libmpv calls away from the AppKit/WebKit main thread");
assert.match(mpvEmbedSource, /async fn mpv_embed_set_loop_file[\s\S]*run_mpv_command/, "macOS mpv loop commands must run libmpv calls away from the AppKit/WebKit main thread");
assert.match(mpvEmbedSource, /async fn mpv_embed_snapshot[\s\S]*run_mpv_command/, "periodic mpv snapshots must not block the AppKit/WebKit main thread");
assert.match(mpvEmbedSource, /tauri::async_runtime::spawn_blocking/, "mpv command dispatch must use a blocking worker to avoid AppKit/libmpv main-thread deadlocks on macOS");
assert.doesNotMatch(mpvSnapshotSource, /host\.resize/, "mpv snapshots must not resize the AppKit video host while holding the player mutex");
assert.match(mpvEmbedSource, /mpv_embed_set_video_fill[\s\S]*set_property\("panscan"[\s\S]*1\.0[\s\S]*0\.0/, "mpv video fill must use panscan only when the explicit video layout option is enabled");
assert.match(mpvEmbedSource, /fn window_mpv_wid/, "mpv native video host must map raw platform handles to mpv wid values");
assert.match(mpvEmbedSource, /fn wid\(&self\) -> i64/, "mpv native video host must expose a platform-owned mpv wid boundary");
assert.match(mpvEmbedSource, /mpv_embed_snapshot[\s\S]*player\.snapshot\(0,\s*"playing"\)/, "periodic mpv snapshots must preserve playing status so smooth progress, frame labels, and Space pause keep working");
assert.match(mpvEmbedSource, /input-default-bindings"[\s\S]*false/, "embedded mpv must not keep its own default keyboard bindings when the video background has focus");
assert.match(mpvEmbedSource, /input-vo-keyboard"[\s\S]*false/, "embedded mpv video output must not consume OpenPlayer shortcuts");
assert.match(mpvEmbedSource, /force_paused_until/, "frame stepping must guard snapshots against mpv's transient unpaused frame-step state");
assert.match(mpvEmbedSource, /FRAME_STEP_PAUSE_GUARD/, "frame stepping must define a bounded paused-state guard");
assert.match(mpvEmbedSource, /settle_frame_step_pause/, "frame stepping must wait briefly for mpv to return to paused state");
assert.match(mpvEmbedSource, /raw_paused\s*\|\|\s*pause_guard_active/, "snapshots must report paused while the frame-step guard is active");

assert.doesNotMatch(tauriLibSource, /mod playback;|mod storage|DesktopPlaybackState|DesktopStorageState|playback_command|storage_|openplayer_core|openplayer_shared/, "desktop backend must not restore removed playback or storage plumbing");
assert.match(tauriLibSource, /window_minimize/, "desktop backend must keep minimize command");
assert.match(tauriLibSource, /window_toggle_maximize/, "desktop backend must keep maximize command");
assert.match(tauriLibSource, /window_toggle_fullscreen[\s\S]*main_window\(&app\)\?[\s\S]*set_main_window_fullscreen/, "desktop backend must toggle fullscreen on the main video window");
assert.match(windowToggleFullscreenSource, /fullscreen_restore[\s\S]*is_some\(\)[\s\S]*is_fullscreen/, "fullscreen restore state must be treated as authoritative so one middle click exits macOS fullscreen transitions");
assert.doesNotMatch(windowToggleFullscreenSource, /set_fullscreen_video_fill|mpv_embed_set_video_fill|panscan/, "fullscreen toggling must preserve mpv's current video layout instead of forcing fill/crop");
assert.match(tauriLibSource, /#\[cfg\(target_os = "macos"\)\][\s\S]*fn set_main_window_fullscreen[\s\S]*prepare_macos_main_window_chrome[\s\S]*set_fullscreen/, "macOS fullscreen should keep native fullscreen but hide AppKit titlebar chrome before transitions");
assert.match(macosGlViewSource, /openplayer_macos_prepare_main_window[\s\S]*titleVisibility[\s\S]*titlebarAppearsTransparent[\s\S]*standardWindowButton/, "macOS main window must hide native titlebar controls to avoid titlebar flashes during fullscreen transitions");
assert.match(tauriLibSource, /struct WindowPlacement/, "desktop backend must record window placement before entering fullscreen");
assert.match(tauriLibSource, /restore_window_after_fullscreen/, "desktop backend must restore the recorded placement after leaving fullscreen");
assert.match(tauriLibSource, /fn focus_overlay_window/, "desktop backend must provide a shared way to focus the overlay controls window");
assert.match(tauriLibSource, /fn window_focus_overlay/, "desktop backend must expose an overlay focus command for frontend shortcut recovery");
assert.match(tauriLibSource, /fn window_update_shortcuts/, "desktop backend must accept current custom shortcuts for native dispatch");
assert.match(tauriLibSource, /mod appearance_store;/, "desktop backend must include the redb-backed appearance settings store module");
assert.match(tauriLibSource, /AppearanceStoreState/, "desktop backend must manage appearance settings store state");
assert.match(tauriLibSource, /appearance_state[\s\S]*appearance_set_theme[\s\S]*appearance_set_accent_override[\s\S]*appearance_import_theme_plugin[\s\S]*appearance_set_plugin_enabled[\s\S]*appearance_reset/, "desktop runtime must register appearance and theme plugin commands");
assert.match(tauriLibSource, /preferences_state[\s\S]*preferences_set_incognito_mode[\s\S]*preferences_set_quiet_keyboard_controls[\s\S]*preferences_set_language_mode/, "desktop runtime must register persisted player preference commands");
assert.match(appearanceStoreSource, /with_store[\s\S]*AppearanceStore::open/, "appearance settings commands must open redb per command so multiple OpenPlayer processes do not hold the database lock forever");
assert.match(tauriLibSource, /mod playback_store;/, "desktop backend must include the playback history store module");
assert.match(tauriLibSource, /mod media_paths;/, "desktop backend must include media path scanning and startup path support");
assert.match(tauriLibSource, /mod shell_preview;/, "desktop backend must include Windows Explorer preview registration");
assert.match(tauriLibSource, /shell_preview_formats[\s\S]*shell_preview_register_formats/, "desktop runtime must register Explorer preview format list and selected-format registration commands");
assert.match(shellPreviewSource, /ShellPreviewFormat::video(?:_common)?\("mp4",\s*"video\/mp4"\)/, "Explorer preview registration must cover MP4");
assert.match(shellPreviewSource, /ShellPreviewFormat::video(?:_common)?\("mkv",\s*"video\/x-matroska"\)/, "Explorer preview registration must cover Matroska video");
assert.match(shellPreviewSource, /ShellPreviewFormat::video\("mxf",\s*"application\/mxf"\)/, "Explorer preview registration must cover broader mpv video containers");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio_common\("mp3",\s*"audio\/mpeg"\)/, "Explorer preview registration must visibly include MP3 audio");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio_common\("wav",\s*"audio\/wav"\)/, "Explorer preview registration must visibly include WAV audio");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio_common\("m4b",\s*"audio\/mp4"\)/, "Explorer preview registration must cover common audiobook audio");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio\("amr",\s*"audio\/amr"\)/, "Explorer preview registration must cover mobile AMR audio");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio\("caf",\s*"audio\/x-caf"\)/, "Explorer preview registration must cover Core Audio files");
assert.match(shellPreviewSource, /ShellPreviewFormat::audio\("wv",\s*"audio\/x-wavpack"\)/, "Explorer preview registration must cover broader mpv audio containers");
assert.match(shellPreviewSource, /common:\s*true/, "Explorer preview formats must mark common defaults separately from the full catalog");
assert.match(shellPreviewSource, /selected_extensions[\s\S]*filter_preview_formats/, "Explorer preview registration must filter the catalog by selected extensions");
assert.match(shellPreviewSource, /register_openplayer_handlers/, "Explorer preview registration must also register OpenPlayer as an available handler for selected formats");
assert.match(shellPreviewSource, /RegisteredApplications/, "Explorer preview registration must expose OpenPlayer in Windows default-app capabilities");
assert.match(shellPreviewSource, /OpenWithProgids/, "Explorer preview registration must add OpenPlayer to each selected extension's Open With handlers");
assert.match(shellPreviewSource, /OpenWithList/, "Explorer preview registration must add OpenPlayer to the Windows Open With application list");
assert.match(shellPreviewSource, /ms-settings:defaultapps/, "Explorer preview settings command must open Windows default apps settings");
assert.match(shellPreviewSource, /current_exe\(\)[\s\S]*file_name\(\)/, "Explorer preview registration must use the installed executable name for Windows application handlers");
assert.doesNotMatch(shellPreviewSource, /pub fn shell_preview_register_all/, "backend must not expose an all-format preview registration command");
assert.match(shellPreviewSource, /SHChangeNotify/, "Explorer preview registration must notify Windows Shell after registry updates");
assert.match(tauriLibSource, /StartupMediaState::from_args\(std::env::args_os\(\)\)/, "desktop runtime must capture file-association startup media paths");
assert.match(tauriLibSource, /media_files_in_directory[\s\S]*startup_media_paths/, "desktop runtime must register media folder scanning and startup path commands");
assert.match(mediaPathsSource, /collect_media_files_in_directory[\s\S]*sort_media_paths/, "media folder scanner must return naturally sorted media files");
assert.match(mediaPathsSource, /StartupMediaState[\s\S]*from_args[\s\S]*is_supported_media_path/, "startup media state must filter command-line args to supported media files");
assert.match(tauriLibSource, /PlaybackStoreState/, "desktop backend must manage playback history store state");
assert.match(tauriLibSource, /history_list[\s\S]*history_remember[\s\S]*history_resume_position[\s\S]*history_clear/, "desktop runtime must register playback history commands including clear");
assert.match(tauriCargoToml, /redb/, "desktop backend must depend on redb for high-performance playback history storage");
assert.match(playbackStoreSource, /redb::Database|use redb::\{Database/, "playback history store must use redb");
assert.match(playbackStoreSource, /with_store[\s\S]*PlaybackStore::open/, "playback history commands must open redb per command so secondary windows can read and write history");
assert.match(playbackStoreSource, /HISTORY_BY_PATH/, "playback history store must index entries by path");
assert.match(playbackStoreSource, /HISTORY_BY_UPDATED/, "playback history store must index entries by recency");
assert.match(playbackStoreSource, /resume_position_for_entry/, "playback history store must compute resume positions by ratio");
assert.match(playbackStoreSource, /RESUME_END_PROGRESS_RATIO/, "playback history store must define a relative end threshold");
assert.match(appearanceStoreSource, /openplayer-settings\.redb/, "appearance settings must use a dedicated redb database instead of playback history storage");
assert.match(appearanceStoreSource, /SETTINGS_KV/, "appearance store must persist active theme and accent settings");
assert.match(appearanceStoreSource, /THEME_MANIFESTS/, "appearance store must persist imported theme manifests");
assert.match(appearanceStoreSource, /PLUGIN_MANIFESTS/, "appearance store must persist imported plugin manifests");
assert.match(appearanceStoreSource, /PLUGIN_ENABLEMENT/, "appearance store must persist plugin enablement");
assert.match(appearanceStoreSource, /ThemePluginEntry[\s\S]*manifest/, "theme plugins must remain manifest-only in this slice");
assert.match(appearanceStoreSource, /PlayerPreferences/, "appearance settings store must persist player preferences in the shared settings database");
assert.match(appearanceStoreSource, /INCOGNITO_MODE_KEY/, "settings store must persist incognito mode");
assert.match(appearanceStoreSource, /QUIET_KEYBOARD_CONTROLS_KEY/, "settings store must persist quiet keyboard controls");
assert.match(appearanceStoreSource, /LANGUAGE_MODE_KEY/, "settings store must persist language mode");
assert.match(appearanceStoreSource, /deny_unknown_fields/, "theme and plugin manifests must reject unknown fields");
assert.match(appearanceStoreSource, /validate_color_token/, "appearance store must validate theme color tokens before persisting manifests");
assert.match(tauriLibSource, /fn window_set_shortcuts_enabled/, "desktop backend must allow frontend modal states to suspend native shortcut dispatch");
assert.match(tauriLibSource, /fn install_native_shortcut_hook/, "desktop backend must install a native shortcut bridge for focus-independent shortcuts on Windows");
assert.match(tauriLibSource, /SetWindowsHookExW/, "Windows shortcut bridge must use a low-level keyboard hook while the app is focused");
assert.match(tauriLibSource, /GetModuleHandleW/, "Windows shortcut hook must pass the current module handle instead of silently failing with a null module");
assert.match(tauriLibSource, /GetForegroundWindow/, "Windows shortcut bridge must only dispatch shortcuts when OpenPlayer is the foreground app");
assert.match(tauriLibSource, /openplayer-native-shortcut/, "native shortcut bridge must emit actions to the overlay frontend");
assert.match(tauriLibSource, /sync_overlay_to_main[\s\S]*focus_overlay_window\(app\)/, "overlay sync must return keyboard focus to the controls window");
assert.match(tauriLibSource, /openplayer_macos_prepare_overlay_window/, "macOS overlay window must be marked as a fullscreen auxiliary child of the video window");
assert.match(macosGlViewSource, /NSWindowCollectionBehaviorFullScreenAuxiliary[\s\S]*addChildWindow/, "macOS overlay must join the main video fullscreen space instead of creating a separate fullscreen space");
assert.match(tauriLibSource, /WindowEvent::Focused\(true\)[\s\S]*focus_overlay_window\(&app_handle\)/, "clicking the video/main window must return keyboard focus to the overlay shortcut handler");
assert.match(tauriLibSource, /fn schedule_overlay_sync_to_main/, "desktop backend must schedule overlay sync after asynchronous fullscreen transitions");
assert.match(windowToggleFullscreenSource, /schedule_overlay_sync_to_main\(&app\)/, "fullscreen toggling must defer overlay sync until the main window has applied fullscreen bounds");
assert.doesNotMatch(windowToggleFullscreenSource, /sync_overlay_to_main\(&app\)/, "fullscreen toggling must not immediately sync the overlay using stale fullscreen transition bounds");
assert.match(mpvEmbedRunSource, /mpv_embed_frame_step[\s\S]*mpv_embed_frame_back_step[\s\S]*mpv_embed_set_speed[\s\S]*mpv_embed_set_video_fill[\s\S]*mpv_embed_set_subtitle_delay[\s\S]*mpv_embed_select_track[\s\S]*mpv_embed_add_subtitle/, "desktop runtime must register frame, speed, video layout, subtitle delay, track, and subtitle mpv commands");
assert.match(tauriLibSource, /window_start_resize[\s\S]*start_resize_dragging/, "desktop backend must start resizing the main video window from overlay hit areas");
assert.match(tauriLibSource, /fn window_set_resize_cursor[\s\S]*CursorIcon::NeResize[\s\S]*CursorIcon::Default/, "desktop backend must expose native resize cursor icons for overlay hit areas");
assert.match(windowApplyResizeDeltaSource, /set_position[\s\S]*set_size/, "macOS manual resize fallback must resize the main video window");
assert.doesNotMatch(windowApplyResizeDeltaSource, /sync_overlay_to_main|sync_mpv_video_host/, "macOS manual resize deltas must not run immediate duplicate overlay/mpv sync on every pointermove");
assert.match(tauriLibSource, /window_close/, "desktop backend must keep close command");
assert.match(tauriLibSource, /window_start_drag[\s\S]*main_window\(&app\)\?[\s\S]*start_dragging/, "backend must drag the main video window when overlay drag strip is used");
assert.match(mainSource, /windows_subsystem\s*=\s*"windows"/, "release Windows app must use GUI subsystem instead of opening a console");

assert.ok(!capability.permissions.includes("core:window:allow-start-dragging"), "capability must not allow the removed JS start_dragging path");
assert.ok(capability.permissions.includes("core:window:allow-set-fullscreen"), "capability must allow fullscreen toggling");
assert.ok(capability.permissions.includes("core:window:allow-is-fullscreen"), "capability must allow reading fullscreen state");
assert.ok(capability.permissions.includes("dialog:allow-open"), "capability must allow native file dialog for mpv path playback");

assert.match(workspaceToml, /members = \[\s*"apps\/desktop\/src-tauri",\s*\]/, "workspace should only build the desktop shell crate");
assert.doesNotMatch(workspaceToml, /crates\//, "minimal workspace must not include old backend crates");
