import type { MediaItem } from "../../app/types";
import type { usePlayerInteractionRuntime } from "../../hooks/usePlayerInteractionRuntime";
import type { usePlayerOverlayFoundation } from "../../hooks/usePlayerOverlayFoundation";
import type { usePlayerOverlayState } from "../../hooks/usePlayerOverlayState";
import type { usePlayerPlaybackCoordinator } from "../../hooks/usePlayerPlaybackCoordinator";
import type { usePlayerWorkspaceDomains } from "../../hooks/usePlayerWorkspaceDomains";
import { buildPlayerOverlayViewProps } from "./playerOverlayViewProps";
import type { PlayerAppViewProps, PlayerAppViewPropsContext } from "./viewProps/types";

type PlayerOverlayDomainsInput = {
  media: MediaItem | null;
  state: ReturnType<typeof usePlayerOverlayState>;
  foundation: ReturnType<typeof usePlayerOverlayFoundation>;
  playback: ReturnType<typeof usePlayerPlaybackCoordinator>;
  workspace: ReturnType<typeof usePlayerWorkspaceDomains>;
  interaction: ReturnType<typeof usePlayerInteractionRuntime>;
  onWindowCommand: PlayerAppViewPropsContext["onWindowCommand"];
};

export function buildPlayerOverlayViewPropsFromDomains({
  media,
  state,
  foundation,
  playback,
  workspace,
  interaction,
  onWindowCommand,
}: PlayerOverlayDomainsInput): PlayerAppViewProps {
  const { mediaDomain, settings, windowActions } = workspace;
  const { chrome, lifecycle, pluginRuntime } = interaction;

  return buildPlayerOverlayViewProps({
    appearanceStyle: settings.appearanceStyle,
    media,
    shellHandlers: chrome.shellHandlers,
    t: foundation.t,
    locale: foundation.locale,
    platformSupport: state.platformSupport,
    isPlaying: state.isPlaying,
    displayTime: playback.displayTime,
    duration: state.duration,
    resizeFeedback: chrome.resizeFeedback,
    isDropActive: lifecycle.isDropActive,
    playbackError: foundation.playbackError,
    volumeFeedback: foundation.volumeFeedback,
    alwaysOnTopFeedback: foundation.alwaysOnTopFeedback,
    captureFeedback: foundation.captureFeedback,
    recordingState: state.recordingState,
    onWindowCommand,
    handleDragRegionDoubleClick: chrome.handleDragRegionDoubleClick,
    handleDragRegionPointerDown: chrome.handleDragRegionPointerDown,
    handleDragRegionPointerMove: chrome.handleDragRegionPointerMove,
    handleDragRegionPointerEnd: chrome.handleDragRegionPointerEnd,
    handleResizePointerEnter: chrome.handleResizePointerEnter,
    handleResizePointerLeave: chrome.handleResizePointerLeave,
    handleResizePointerDown: chrome.handleResizePointerDown,
    handleResizePointerMove: chrome.handleResizePointerMove,
    handleResizePointerEnd: chrome.handleResizePointerEnd,
    isPickerOpen: state.isPickerOpen,
    mediaPanelMode: foundation.mediaPanelMode,
    volumeLevel: state.volumeLevel,
    playbackSpeed: state.playbackSpeed,
    isPlaylistOpen: foundation.isPlaylistOpen,
    hardwareDecodingMode: state.hardwareDecodingMode,
    pluginControlLeftActions: pluginRuntime.pluginControlLeftActions,
    pluginControlCenterActions: pluginRuntime.pluginControlCenterActions,
    pluginControlRightActions: pluginRuntime.pluginControlRightActions,
    pluginPlaylistActions: pluginRuntime.pluginPlaylistActions,
    isPluginActionDisabled: pluginRuntime.isPluginActionDisabled,
    executePluginAction: pluginRuntime.executePluginAction,
    toggleTimeDisplayMode: playback.toggleTimeDisplayMode,
    playPreviousQueueItem: mediaDomain.playPreviousQueueItem,
    seekTo: playback.seekTo,
    commitSeekTo: playback.commitSeekTo,
    playNextQueueItem: mediaDomain.playNextQueueItem,
    openNativeMediaFiles: mediaDomain.openNativeMediaFiles,
    stopPlayback: playback.stopPlayback,
    togglePlayback: playback.togglePlayback,
    toggleLoopPanel: foundation.toggleLoopPanel,
    toggleMute: playback.toggleMute,
    setVolume: playback.setVolume,
    toggleSpeedPanel: foundation.toggleSpeedPanel,
    toggleTrackPanel: foundation.toggleTrackPanel,
    togglePlaylist: foundation.togglePlaylist,
    toggleHardwareDecoding: playback.toggleHardwareDecoding,
    loopMode: state.loopMode,
    loopModeOptions: foundation.loopModeOptions,
    setPlaybackSpeed: playback.setPlaybackSpeed,
    setLoopMode: playback.setLoopMode,
    isVideoFillEnabled: state.isVideoFillEnabled,
    subtitleDelay: state.subtitleDelay,
    systemFontFamilies: state.systemFontFamilies,
    setVideoFillMode: playback.setVideoFillMode,
    selectTrack: mediaDomain.selectTrack,
    setSubtitleDelay: mediaDomain.setSubtitleDelay,
    setPluginSettingValue: settings.setPluginSettingValue,
    choosePluginDirectory: settings.choosePluginDirectory,
    openPluginDirectory: settings.openPluginDirectory,
    addExternalSubtitle: mediaDomain.addExternalSubtitle,
    currentIndex: state.currentIndex,
    playbackHistory: state.playbackHistory,
    appendNativeMediaFiles: mediaDomain.appendNativeMediaFiles,
    appendNativeMediaFolder: mediaDomain.appendNativeMediaFolder,
    chooseQueueItem: mediaDomain.chooseQueueItem,
    openHistoryEntry: mediaDomain.openHistoryEntry,
    clearPlaybackHistory: mediaDomain.clearPlaybackHistory,
    contextMenu: foundation.contextMenu,
    setContextMenu: foundation.setContextMenu,
    activePluginView: mediaDomain.activePluginView,
    activePluginViewDocument: mediaDomain.activePluginViewDocument,
    pluginViewFrameRef: mediaDomain.pluginViewFrameRef,
    closePluginView: mediaDomain.closePluginView,
    isNetworkStreamDialogOpen: mediaDomain.isNetworkStreamDialogOpen,
    networkStreamUrl: mediaDomain.networkStreamUrl,
    networkStreamError: mediaDomain.networkStreamError,
    networkStreamHistory: mediaDomain.networkStreamHistory,
    closeNetworkStreamDialog: mediaDomain.closeNetworkStreamDialog,
    submitNetworkStream: mediaDomain.submitNetworkStream,
    setNetworkStreamUrl: mediaDomain.setNetworkStreamUrl,
    setNetworkStreamError: mediaDomain.setNetworkStreamError,
    clearNetworkStreamHistory: mediaDomain.clearNetworkStreamHistory,
    openNetworkStreamHistoryEntry: mediaDomain.openNetworkStreamHistoryEntry,
    isSettingsOpen: settings.isSettingsOpen,
    settingsDialogRef: settings.settingsDialogRef,
    settingsSection: settings.settingsSection,
    appearanceState: state.appearanceState,
    activeTheme: settings.activeTheme,
    playerPreferences: state.playerPreferences,
    expandedPluginIds: settings.expandedPluginIds,
    shellPreviewFormats: settings.shellPreviewFormats,
    selectedShellPreviewFormats: settings.selectedShellPreviewFormats,
    shellPreviewRegistrationStatus: settings.shellPreviewRegistrationStatus,
    isRegisteringShellPreview: settings.isRegisteringShellPreview,
    shortcutDefinitions: foundation.shortcutDefinitions,
    shortcutBindings: foundation.shortcutBindings,
    recordingShortcutAction: foundation.recordingShortcutAction,
    appVersion: state.appVersion,
    updateState: lifecycle.updateState,
    setSettingsSection: settings.setSettingsSection,
    closeSettingsDialog: settings.closeSettingsDialog,
    resetAppearance: settings.resetAppearance,
    selectTheme: settings.selectTheme,
    setAccentOverride: settings.setAccentOverride,
    setLanguageMode: settings.setLanguageMode,
    importPluginPackage: settings.importPluginPackage,
    importPluginDirectory: settings.importPluginDirectory,
    importThemePlugin: settings.importThemePlugin,
    openExternalUrl: windowActions.openExternalUrl,
    setThemePluginEnabled: settings.setThemePluginEnabled,
    togglePluginSettingsExpanded: settings.togglePluginSettingsExpanded,
    uninstallPlugin: settings.uninstallPlugin,
    setIncognitoMode: settings.setIncognitoMode,
    setQuietKeyboardControls: settings.setQuietKeyboardControls,
    toggleAllShellPreviewFormats: settings.toggleAllShellPreviewFormats,
    resetShellPreviewFormatsToDefault: settings.resetShellPreviewFormatsToDefault,
    openDefaultAppsSettings: settings.openDefaultAppsSettings,
    registerShellPreviews: settings.registerShellPreviews,
    toggleShellPreviewFormat: settings.toggleShellPreviewFormat,
    resetShortcutBindings: foundation.resetShortcutBindings,
    setRecordingShortcutAction: foundation.setRecordingShortcutAction,
    assignShortcut: foundation.assignShortcut,
    checkForUpdates: lifecycle.checkForUpdates,
    openUpdateDownload: lifecycle.openUpdateDownload,
    queue: state.queue,
    loadedMediaPath: state.loadedMediaPath,
    tracks: state.tracks,
    framesPerSecond: state.framesPerSecond,
    timeDisplayMode: state.timeDisplayMode,
    isChromeVisible: chrome.isChromeVisible,
    isChromePinned: chrome.isChromePinned,
    previousQueueIndex: mediaDomain.previousQueueIndex,
    nextQueueIndex: mediaDomain.nextQueueIndex,
    isAlwaysOnTop: state.isAlwaysOnTop,
    pluginContextMenuActions: pluginRuntime.pluginContextMenuActions,
    restartPlayback: playback.restartPlayback,
    toggleFullscreen: windowActions.toggleFullscreen,
    toggleAlwaysOnTop: windowActions.toggleAlwaysOnTop,
    openSettingsDialog: settings.openSettingsDialog,
    openCurrentFileLocation: windowActions.openCurrentFileLocation,
  });
}
