//! Trusted developer adapter only. The script is generated by the host fixture.
use super::*;
use std::{
    io::Write,
    sync::atomic::{AtomicBool, AtomicU64, Ordering},
};

static CLAIMED: AtomicBool = AtomicBool::new(false);
static SEQUENCE: AtomicU64 = AtomicU64::new(1);

pub(crate) struct OwnedFilter {
    app: AppHandle,
    script: PathBuf,
    label: String,
    script_created: bool,
}

impl OwnedFilter {
    pub(crate) fn prepare(
        app: AppHandle,
        directory: &Path,
        endpoint: &Value,
    ) -> Result<Self, String> {
        if CLAIMED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return Err("another native video attachment owns the player".into());
        }
        let label = format!("native-owned-{}", SEQUENCE.fetch_add(1, Ordering::Relaxed));
        let mut filter = Self {
            app,
            script: directory.join(format!("{label}.vpy")),
            label,
            script_created: false,
        };
        let encoded = serde_json::to_string(&endpoint.to_string()).map_err(|e| e.to_string())?;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&filter.script)
            .map_err(|e| e.to_string())?;
        filter.script_created = true;
        write!(file, "import json\nfrom host_vapoursynth import create_filter\ncreate_filter(video_in, json.loads({encoded})).set_output()\n")
            .map_err(|e| e.to_string())?;
        Ok(filter)
    }

    pub(crate) fn install(&self) -> Result<(), String> {
        let script = self.script.to_str().ok_or("non-UTF8 adapter path")?;
        let filter = format!(
            "@{}:vapoursynth=file=%{}%{}:concurrent-frames=1",
            self.label,
            script.len(),
            script
        );
        let state = self.app.state::<MpvEmbedState>();
        with_player(state.inner(), |player| {
            player
                .mpv
                .command("vf", &["add", &filter])
                .map_err(|e| e.to_string())
        })
    }

    pub(crate) fn remove(&self) -> Result<(), String> {
        let state = self.app.state::<MpvEmbedState>();
        let player = state.player.lock().map_err(|_| "mpv state unavailable")?;
        // No player means its filter was already destroyed on stop/replacement.
        if let Some(player) = player.as_ref() {
            player
                .mpv
                .command("vf", &["remove", &format!("@{}", self.label)])
                .map_err(|e| e.to_string())?;
        }
        Ok(())
    }
}

impl Drop for OwnedFilter {
    fn drop(&mut self) {
        if self.script_created {
            let _ = std::fs::remove_file(&self.script);
        }
        CLAIMED.store(false, Ordering::Release);
    }
}

pub(crate) fn filters(app: &AppHandle) -> Result<String, String> {
    with_player(app.state::<MpvEmbedState>().inner(), |p| {
        p.mpv
            .get_property::<String>("vf")
            .map_err(|e| e.to_string())
    })
}
