import type { PlayerAppViewProps, PlayerAppViewPropsContext } from "./types";

export function buildDialogViewProps({
  t,
  locale,
  media,
  contextMenu,
  contextMenuItems,
  setContextMenu,
  activePluginView,
  activePluginViewDocument,
  pluginViewFrameRef,
  closePluginView,
  isNetworkStreamDialogOpen,
  networkStreamUrl,
  networkStreamError,
  networkStreamHistory,
  closeNetworkStreamDialog,
  submitNetworkStream,
  setNetworkStreamUrl,
  setNetworkStreamError,
  clearNetworkStreamHistory,
  openNetworkStreamHistoryEntry,
  isSettingsOpen,
  settingsDialogRef,
  settingsSection,
  appearanceState,
  activeTheme,
  playerPreferences,
  pluginRuntimeLogs,
  playbackHistory,
  expandedPluginIds,
  isPickerOpen,
  systemFontFamilies,
  shellPreviewFormats,
  selectedShellPreviewFormats,
  shellPreviewRegistrationStatus,
  isRegisteringShellPreview,
  shortcutDefinitions,
  shortcutBindings,
  recordingShortcutAction,
  appVersion,
  updateState,
  setSettingsSection,
  closeSettingsDialog,
  resetAppearance,
  selectTheme,
  setAccentOverride,
  setLanguageMode,
  importPluginPackage,
  importPluginDirectory,
  importThemePlugin,
  openExternalUrl,
  setThemePluginEnabled,
  togglePluginSettingsExpanded,
  uninstallPlugin,
  setPluginSettingValue,
  choosePluginDirectory,
  openPluginDirectory,
  clearPlaybackHistory,
  setIncognitoMode,
  setQuietKeyboardControls,
  toggleAllShellPreviewFormats,
  resetShellPreviewFormatsToDefault,
  openDefaultAppsSettings,
  registerShellPreviews,
  toggleShellPreviewFormat,
  resetShortcutBindings,
  setRecordingShortcutAction,
  assignShortcut,
  checkForUpdates,
  openUpdateDownload,
}: PlayerAppViewPropsContext): Pick<
  PlayerAppViewProps,
  "contextMenuProps" | "pluginViewShellProps" | "networkStreamDialogProps" | "settingsDialogProps"
> {
  return {
    contextMenuProps: contextMenu
      ? {
          t,
          position: contextMenu,
          items: contextMenuItems,
          onClose: () => setContextMenu(null),
        }
      : null,
    pluginViewShellProps: activePluginView && activePluginViewDocument
      ? {
          t,
          activePluginView,
          documentHtml: activePluginViewDocument,
          frameRef: pluginViewFrameRef,
          onClose: closePluginView,
        }
      : null,
    networkStreamDialogProps: isNetworkStreamDialogOpen
      ? {
          t,
          networkStreamUrl,
          networkStreamError,
          networkStreamHistory,
          onClose: closeNetworkStreamDialog,
          onSubmit: submitNetworkStream,
          onUrlChange: (value) => {
            setNetworkStreamUrl(value);
            setNetworkStreamError(null);
          },
          onClearHistory: clearNetworkStreamHistory,
          onOpenHistoryEntry: openNetworkStreamHistoryEntry,
        }
      : null,
    settingsDialogProps: isSettingsOpen
      ? {
          t,
          locale,
          dialogRef: settingsDialogRef,
          settingsSection,
          appearanceState,
          activeTheme,
          playerPreferences,
          playbackHistoryLength: playbackHistory.length,
          plugins: appearanceState?.plugins ?? [],
          pluginRuntimeLogs,
          expandedPluginIds,
          isPickerOpen,
          systemFontFamilies,
          shellPreviewFormats,
          selectedShellPreviewFormats,
          shellPreviewRegistrationStatus,
          isRegisteringShellPreview,
          shortcutDefinitions,
          shortcutBindings,
          recordingShortcutAction,
          appVersion,
          updateState,
          onSectionChange: setSettingsSection,
          onClose: closeSettingsDialog,
          onResetAppearance: resetAppearance,
          onSelectTheme: selectTheme,
          onSetAccentOverride: setAccentOverride,
          onSetLanguageMode: setLanguageMode,
          onImportPluginPackage: importPluginPackage,
          onImportPluginDirectory: importPluginDirectory,
          onImportThemePlugin: importThemePlugin,
          onOpenExternalUrl: openExternalUrl,
          onSetPluginEnabled: setThemePluginEnabled,
          onTogglePluginSettingsExpanded: togglePluginSettingsExpanded,
          onUninstallPlugin: uninstallPlugin,
          onSetPluginSettingValue: setPluginSettingValue,
          onChoosePluginDirectory: choosePluginDirectory,
          onOpenPluginDirectory: openPluginDirectory,
          onClearPlaybackHistory: clearPlaybackHistory,
          onSetIncognitoMode: setIncognitoMode,
          onSetQuietKeyboardControls: setQuietKeyboardControls,
          onToggleAllShellPreviewFormats: toggleAllShellPreviewFormats,
          onResetShellPreviewFormatsToDefault: resetShellPreviewFormatsToDefault,
          onOpenDefaultAppsSettings: openDefaultAppsSettings,
          onRegisterShellPreviews: registerShellPreviews,
          onToggleShellPreviewFormat: toggleShellPreviewFormat,
          onResetShortcutBindings: resetShortcutBindings,
          onStartRecordingShortcut: setRecordingShortcutAction,
          onAssignShortcut: assignShortcut,
          onCheckForUpdates: checkForUpdates,
          onOpenUpdateDownload: openUpdateDownload,
        }
      : null,
  };
}
