import type { PlayerAppViewProps, PlayerAppViewPropsContext } from "./types";

export function buildTransportViewProps({
  t,
  locale,
  media,
  duration,
  displayTime,
  progress,
  progressRatio,
  effectiveTimeDisplayMode,
  canShowFrames,
  currentTransportLabel,
  durationTransportLabel,
  currentTimeToggleLabel,
  durationTimeToggleLabel,
  previousIndex,
  nextIndex,
  isPickerOpen,
  isPlaying,
  mediaPanelMode,
  isMuted,
  volumeMuteLabel,
  volumeLevel,
  playbackSpeed,
  isPlaylistOpen,
  hardwareDecodingMode,
  hardwareDecodingLabel,
  hardwareDecodingToggleLabel,
  pluginControlLeftActions,
  pluginControlCenterActions,
  pluginControlRightActions,
  isPluginActionDisabled,
  executePluginAction,
  toggleTimeDisplayMode,
  playPreviousQueueItem,
  seekTo,
  commitSeekTo,
  playNextQueueItem,
  openNativeMediaFiles,
  stopPlayback,
  togglePlayback,
  toggleLoopPanel,
  toggleMute,
  setVolume,
  toggleSpeedPanel,
  toggleTrackPanel,
  togglePlaylist,
  toggleHardwareDecoding,
}: PlayerAppViewPropsContext): Pick<PlayerAppViewProps, "transportControlsProps"> {
  return {
    transportControlsProps: {
      t,
      locale,
      mediaLoaded: Boolean(media),
      duration,
      displayTime,
      progress,
      progressRatio,
      effectiveTimeDisplayMode,
      canShowFrames,
      currentTransportLabel,
      durationTransportLabel,
      currentTimeToggleLabel,
      durationTimeToggleLabel,
      previousIndex,
      nextIndex,
      isPickerOpen,
      isPlaying,
      mediaPanelMode,
      isMuted,
      volumeMuteLabel,
      volumeLevel,
      playbackSpeed,
      isPlaylistOpen,
      hardwareDecodingMode,
      hardwareDecodingLabel,
      hardwareDecodingToggleLabel,
      pluginControlLeftActions,
      pluginControlCenterActions,
      pluginControlRightActions,
      isPluginActionDisabled,
      onExecutePluginAction: executePluginAction,
      onToggleTimeDisplayMode: toggleTimeDisplayMode,
      onPlayPreviousQueueItem: playPreviousQueueItem,
      onSeekTo: seekTo,
      onCommitSeekTo: commitSeekTo,
      onPlayNextQueueItem: playNextQueueItem,
      onOpenNativeMediaFiles: openNativeMediaFiles,
      onStopPlayback: stopPlayback,
      onTogglePlayback: togglePlayback,
      onToggleLoopPanel: toggleLoopPanel,
      onToggleMute: toggleMute,
      onSetVolume: setVolume,
      onToggleSpeedPanel: toggleSpeedPanel,
      onToggleTrackPanel: toggleTrackPanel,
      onTogglePlaylist: togglePlaylist,
      onToggleHardwareDecoding: toggleHardwareDecoding,
    },
  };
}
