import type { ComponentProps } from "react";
import type { PlayerAppView } from "../PlayerAppView";

export type PlayerAppViewProps = ComponentProps<typeof PlayerAppView>;

type StageProps = PlayerAppViewProps["stageOverlaysProps"];
type TransportProps = PlayerAppViewProps["transportControlsProps"];
type SpeedPanelProps = NonNullable<PlayerAppViewProps["speedPanelProps"]>;
type LoopPanelProps = NonNullable<PlayerAppViewProps["loopPanelProps"]>;
type TracksPanelProps = NonNullable<PlayerAppViewProps["tracksPanelProps"]>;
type PlaylistDrawerProps = NonNullable<PlayerAppViewProps["playlistDrawerProps"]>;
type ContextMenuProps = NonNullable<PlayerAppViewProps["contextMenuProps"]>;
type PluginViewShellProps = NonNullable<PlayerAppViewProps["pluginViewShellProps"]>;
type NetworkStreamDialogProps = NonNullable<PlayerAppViewProps["networkStreamDialogProps"]>;
type SettingsDialogProps = NonNullable<PlayerAppViewProps["settingsDialogProps"]>;

export type PlayerAppViewPropsContext = {
  appearanceStyle: PlayerAppViewProps["appearanceStyle"];
  media: StageProps["media"];
  isChromeHidden: PlayerAppViewProps["isChromeHidden"];
  shellHandlers: PlayerAppViewProps["shellHandlers"];
  t: StageProps["t"];
  locale: SettingsDialogProps["locale"];
  platformSupport: StageProps["platformSupport"];
  isAudioOnlyMedia: StageProps["isAudioOnlyMedia"];
  isPlaying: StageProps["isPlaying"];
  primaryAudioTrack: StageProps["primaryAudioTrack"];
  displayTime: StageProps["displayTime"];
  duration: StageProps["duration"];
  isDropActive: StageProps["isDropActive"];
  playbackError: StageProps["playbackError"];
  volumeFeedback: StageProps["volumeFeedback"];
  alwaysOnTopFeedback: StageProps["alwaysOnTopFeedback"];
  captureFeedback: StageProps["captureFeedback"];
  recordingState: StageProps["recordingState"];
  onWindowCommand: StageProps["onWindowCommand"];
  handleDragRegionDoubleClick: PlayerAppViewProps["dragRegionHandlers"]["onDoubleClick"];
  handleDragRegionPointerDown: PlayerAppViewProps["dragRegionHandlers"]["onPointerDown"];
  handleDragRegionPointerMove: PlayerAppViewProps["dragRegionHandlers"]["onPointerMove"];
  handleDragRegionPointerEnd: PlayerAppViewProps["dragRegionHandlers"]["onPointerUp"];
  handleResizePointerEnter: PlayerAppViewProps["resizeRegionHandlers"]["onPointerEnter"];
  handleResizePointerLeave: PlayerAppViewProps["resizeRegionHandlers"]["onPointerLeave"];
  handleResizePointerDown: PlayerAppViewProps["resizeRegionHandlers"]["onPointerDown"];
  handleResizePointerMove: PlayerAppViewProps["resizeRegionHandlers"]["onPointerMove"];
  handleResizePointerEnd: PlayerAppViewProps["resizeRegionHandlers"]["onPointerUp"];
  progress: TransportProps["progress"];
  progressRatio: TransportProps["progressRatio"];
  effectiveTimeDisplayMode: TransportProps["effectiveTimeDisplayMode"];
  canShowFrames: TransportProps["canShowFrames"];
  currentTransportLabel: TransportProps["currentTransportLabel"];
  durationTransportLabel: TransportProps["durationTransportLabel"];
  currentTimeToggleLabel: TransportProps["currentTimeToggleLabel"];
  durationTimeToggleLabel: TransportProps["durationTimeToggleLabel"];
  previousIndex: TransportProps["previousIndex"];
  nextIndex: TransportProps["nextIndex"];
  isPickerOpen: TransportProps["isPickerOpen"];
  mediaPanelMode: TransportProps["mediaPanelMode"];
  isMuted: TransportProps["isMuted"];
  volumeMuteLabel: TransportProps["volumeMuteLabel"];
  volumeLevel: TransportProps["volumeLevel"];
  playbackSpeed: TransportProps["playbackSpeed"];
  isPlaylistOpen: TransportProps["isPlaylistOpen"];
  hardwareDecodingMode: TransportProps["hardwareDecodingMode"];
  hardwareDecodingLabel: TransportProps["hardwareDecodingLabel"];
  hardwareDecodingToggleLabel: TransportProps["hardwareDecodingToggleLabel"];
  pluginControlLeftActions: TransportProps["pluginControlLeftActions"];
  pluginControlCenterActions: TransportProps["pluginControlCenterActions"];
  pluginControlRightActions: TransportProps["pluginControlRightActions"];
  pluginPlaylistActions: PlaylistDrawerProps["pluginPlaylistActions"];
  isPluginActionDisabled: TransportProps["isPluginActionDisabled"];
  executePluginAction: TransportProps["onExecutePluginAction"];
  toggleTimeDisplayMode: TransportProps["onToggleTimeDisplayMode"];
  playPreviousQueueItem: TransportProps["onPlayPreviousQueueItem"];
  seekTo: TransportProps["onSeekTo"];
  commitSeekTo: TransportProps["onCommitSeekTo"];
  playNextQueueItem: TransportProps["onPlayNextQueueItem"];
  openNativeMediaFiles: TransportProps["onOpenNativeMediaFiles"];
  stopPlayback: TransportProps["onStopPlayback"];
  togglePlayback: TransportProps["onTogglePlayback"];
  toggleLoopPanel: TransportProps["onToggleLoopPanel"];
  toggleMute: TransportProps["onToggleMute"];
  setVolume: TransportProps["onSetVolume"];
  toggleSpeedPanel: TransportProps["onToggleSpeedPanel"];
  toggleTrackPanel: TransportProps["onToggleTrackPanel"];
  togglePlaylist: TransportProps["onTogglePlaylist"];
  toggleHardwareDecoding: TransportProps["onToggleHardwareDecoding"];
  loopMode: LoopPanelProps["loopMode"];
  loopModeOptions: LoopPanelProps["loopModeOptions"];
  setPlaybackSpeed: SpeedPanelProps["onSetPlaybackSpeed"];
  setLoopMode: LoopPanelProps["onSetLoopMode"];
  isVideoFillEnabled: TracksPanelProps["isVideoFillEnabled"];
  audioTracks: TracksPanelProps["audioTracks"];
  videoTracks: TracksPanelProps["videoTracks"];
  subtitleTracks: TracksPanelProps["subtitleTracks"];
  subtitleDelay: TracksPanelProps["subtitleDelay"];
  subtitlePluginSettingGroups: TracksPanelProps["subtitlePluginSettingGroups"];
  systemFontFamilies: TracksPanelProps["systemFontFamilies"];
  setVideoFillMode: TracksPanelProps["onSetVideoFillMode"];
  selectTrack: TracksPanelProps["onSelectTrack"];
  setSubtitleDelay: TracksPanelProps["onSetSubtitleDelay"];
  setPluginSettingValue: TracksPanelProps["onSetPluginSettingValue"];
  choosePluginDirectory: TracksPanelProps["onChoosePluginDirectory"];
  openPluginDirectory: TracksPanelProps["onOpenPluginDirectory"];
  addExternalSubtitle: TracksPanelProps["onAddExternalSubtitle"];
  queueItems: PlaylistDrawerProps["queueItems"];
  currentIndex: PlaylistDrawerProps["currentIndex"];
  playbackHistory: PlaylistDrawerProps["playbackHistory"];
  appendNativeMediaFiles: PlaylistDrawerProps["onAppendNativeMediaFiles"];
  appendNativeMediaFolder: PlaylistDrawerProps["onAppendNativeMediaFolder"];
  chooseQueueItem: PlaylistDrawerProps["onChooseQueueItem"];
  openHistoryEntry: PlaylistDrawerProps["onOpenHistoryEntry"];
  clearPlaybackHistory: PlaylistDrawerProps["onClearPlaybackHistory"];
  contextMenu: ContextMenuProps["position"] | null;
  contextMenuItems: ContextMenuProps["items"];
  setContextMenu: (position: ContextMenuProps["position"] | null) => void;
  activePluginView: PluginViewShellProps["activePluginView"] | null;
  activePluginViewDocument: PluginViewShellProps["documentHtml"] | null;
  pluginViewFrameRef: PluginViewShellProps["frameRef"];
  closePluginView: PluginViewShellProps["onClose"];
  isNetworkStreamDialogOpen: boolean;
  networkStreamUrl: NetworkStreamDialogProps["networkStreamUrl"];
  networkStreamError: NetworkStreamDialogProps["networkStreamError"];
  networkStreamHistory: NetworkStreamDialogProps["networkStreamHistory"];
  closeNetworkStreamDialog: NetworkStreamDialogProps["onClose"];
  submitNetworkStream: NetworkStreamDialogProps["onSubmit"];
  setNetworkStreamUrl: NetworkStreamDialogProps["onUrlChange"];
  setNetworkStreamError: (error: NetworkStreamDialogProps["networkStreamError"]) => void;
  clearNetworkStreamHistory: NetworkStreamDialogProps["onClearHistory"];
  openNetworkStreamHistoryEntry: NetworkStreamDialogProps["onOpenHistoryEntry"];
  isSettingsOpen: boolean;
  settingsDialogRef: SettingsDialogProps["dialogRef"];
  settingsSection: SettingsDialogProps["settingsSection"];
  appearanceState: SettingsDialogProps["appearanceState"];
  activeTheme: SettingsDialogProps["activeTheme"];
  playerPreferences: SettingsDialogProps["playerPreferences"];
  pluginRuntimeLogs: SettingsDialogProps["pluginRuntimeLogs"];
  expandedPluginIds: SettingsDialogProps["expandedPluginIds"];
  shellPreviewFormats: SettingsDialogProps["shellPreviewFormats"];
  selectedShellPreviewFormats: SettingsDialogProps["selectedShellPreviewFormats"];
  shellPreviewRegistrationStatus: SettingsDialogProps["shellPreviewRegistrationStatus"];
  isRegisteringShellPreview: SettingsDialogProps["isRegisteringShellPreview"];
  shortcutDefinitions: SettingsDialogProps["shortcutDefinitions"];
  shortcutBindings: SettingsDialogProps["shortcutBindings"];
  recordingShortcutAction: SettingsDialogProps["recordingShortcutAction"];
  appVersion: SettingsDialogProps["appVersion"];
  updateState: SettingsDialogProps["updateState"];
  setSettingsSection: SettingsDialogProps["onSectionChange"];
  closeSettingsDialog: SettingsDialogProps["onClose"];
  resetAppearance: SettingsDialogProps["onResetAppearance"];
  selectTheme: SettingsDialogProps["onSelectTheme"];
  setAccentOverride: SettingsDialogProps["onSetAccentOverride"];
  setLanguageMode: SettingsDialogProps["onSetLanguageMode"];
  importPluginPackage: SettingsDialogProps["onImportPluginPackage"];
  importPluginDirectory: SettingsDialogProps["onImportPluginDirectory"];
  importThemePlugin: SettingsDialogProps["onImportThemePlugin"];
  openExternalUrl: SettingsDialogProps["onOpenExternalUrl"];
  setThemePluginEnabled: SettingsDialogProps["onSetPluginEnabled"];
  togglePluginSettingsExpanded: SettingsDialogProps["onTogglePluginSettingsExpanded"];
  uninstallPlugin: SettingsDialogProps["onUninstallPlugin"];
  setIncognitoMode: SettingsDialogProps["onSetIncognitoMode"];
  setQuietKeyboardControls: SettingsDialogProps["onSetQuietKeyboardControls"];
  toggleAllShellPreviewFormats: SettingsDialogProps["onToggleAllShellPreviewFormats"];
  resetShellPreviewFormatsToDefault: SettingsDialogProps["onResetShellPreviewFormatsToDefault"];
  openDefaultAppsSettings: SettingsDialogProps["onOpenDefaultAppsSettings"];
  registerShellPreviews: SettingsDialogProps["onRegisterShellPreviews"];
  toggleShellPreviewFormat: SettingsDialogProps["onToggleShellPreviewFormat"];
  resetShortcutBindings: SettingsDialogProps["onResetShortcutBindings"];
  setRecordingShortcutAction: SettingsDialogProps["onStartRecordingShortcut"];
  assignShortcut: SettingsDialogProps["onAssignShortcut"];
  checkForUpdates: SettingsDialogProps["onCheckForUpdates"];
  openUpdateDownload: SettingsDialogProps["onOpenUpdateDownload"];
};
